"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

type Application = { id:string; reference:string; userEmail:string; userDisplayName:string; fullName:string; birthYear:number; nationality:string; panLast4:string; mobileLast4:string; city:string; state:string; pincode:string; idType:string; evidenceSummary:Record<string,boolean>; status:string; riskLevel:string; reviewNote:string|null; reviewChecks:string[]; reviewedBy:string|null; submittedAt:number; updatedAt:number; reviewedAt:number|null };
type ReviewEvent = { id:string; applicationId:string; actorEmail:string; action:string; note:string|null; checks:string; createdAt:number };
const requiredChecks = [
  {id:"identity",label:"Identity document verified"}, {id:"address",label:"Current address verified"}, {id:"pan",label:"PAN and name matched"},
  {id:"liveness",label:"Selfie/liveness cleared"}, {id:"bank",label:"Bank-account name matched"}, {id:"sanctions",label:"Sanctions and PEP screening cleared"},
];
const enhancedChecks = [{id:"edd",label:"EDD and source-of-funds reviewed"},{id:"senior_management",label:"Senior-management approval recorded"}];

export default function AdminKycClient({ reviewerEmail }:{ reviewerEmail:string }) {
  const [applications,setApplications]=useState<Application[]>([]),[events,setEvents]=useState<ReviewEvent[]>([]),[selectedId,setSelectedId]=useState(""),[checks,setChecks]=useState<string[]>([]),[riskLevel,setRiskLevel]=useState("low"),[note,setNote]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
  const load=useCallback(async()=>{setError("");try{const response=await fetch("/api/admin/kyc",{cache:"no-store"}),data=await response.json();if(!response.ok)throw new Error(data.error||"KYC queue unavailable");setApplications(data.applications);setEvents(data.events);setSelectedId(current=>current||data.applications[0]?.id||"")}catch(reason){setError(reason instanceof Error?reason.message:"KYC queue unavailable")}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const selected=useMemo(()=>applications.find(item=>item.id===selectedId)||null,[applications,selectedId]);
  useEffect(()=>{if(!selected)return;setChecks(selected.reviewChecks||[]);setRiskLevel(["low","medium","high"].includes(selected.riskLevel)?selected.riskLevel:"low");setNote(selected.reviewNote||"");setMessage("");setError("")},[selected]);
  const selectedEvents=events.filter(item=>item.applicationId===selectedId);
  const approvalChecks=riskLevel==="high"?[...requiredChecks,...enhancedChecks]:requiredChecks;
  const decide=async(decision:"approved"|"action_required"|"rejected")=>{if(!selected)return;setSaving(true);setError("");setMessage("");try{const response=await fetch("/api/admin/kyc",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({applicationId:selected.id,decision,riskLevel,note,checks})}),data=await response.json();if(!response.ok)throw new Error(data.error||"Decision could not be saved");setMessage(decision==="approved"?"KYC approved and paper setup unlocked.":decision==="action_required"?"Client update requested.":"KYC rejection recorded.");await load()}catch(reason){setError(reason instanceof Error?reason.message:"Decision could not be saved")}finally{setSaving(false)}};
  const toggle=(id:string)=>setChecks(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);

  return <main className="admin-kyc-shell"><header className="admin-kyc-top"><a href="/"><img src="/chatonyou-logo.png" alt="ChatOnYou"/><b>TRADE</b></a><span>NEOCRAFT LLP · KYC OPERATIONS</span><div><small>Authorised reviewer</small><b>{reviewerEmail}</b><a href="/admin/kyc/provider">Provider</a><a href="/signout-with-chatgpt?return_to=%2Flogin">Sign out</a></div></header>
    <section className="admin-kyc-heading"><div><span>CLIENT ACCEPTANCE CONTROL</span><h1>KYC review queue</h1><p>Every approval requires identity, address, liveness, bank and sanctions checks. All decisions are recorded.</p></div><article><small>PENDING REVIEW</small><b>{applications.filter(item=>item.status==="pending").length}</b><span>{applications.length} total applications</span></article></section>
    {loading?<section className="admin-kyc-loading">Loading protected KYC queue…</section>:error&&!applications.length?<section className="admin-kyc-loading error">{error}</section>:<div className="admin-kyc-layout">
      <aside className="admin-kyc-queue"><header><span>APPLICATIONS</span><button onClick={()=>void load()}>Refresh</button></header>{applications.length?applications.map(item=><button key={item.id} className={selectedId===item.id?"active":""} onClick={()=>setSelectedId(item.id)}><i>{item.fullName.split(/\s+/).slice(0,2).map(part=>part[0]).join("")}</i><span><b>{item.fullName}</b><small>{item.reference} · {item.userEmail}</small></span><em className={`status-${item.status}`}>{item.status.replace("_"," ")}</em></button>):<p>No KYC applications have been submitted.</p>}</aside>
      {selected?<section className="admin-kyc-review"><header><div><span>{selected.reference}</span><h2>{selected.fullName}</h2><p>Submitted {new Date(selected.submittedAt).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"})}</p></div><em className={`status-${selected.status}`}>{selected.status.replace("_"," ")}</em></header>
        <div className="admin-client-grid"><article><small>ACCOUNT EMAIL</small><b>{selected.userEmail}</b></article><article><small>PERSON</small><b>{selected.nationality} · Born {selected.birthYear}</b></article><article><small>PAN</small><b>••••••{selected.panLast4}</b></article><article><small>MOBILE</small><b>Ending {selected.mobileLast4}</b></article><article><small>ADDRESS</small><b>{selected.city}, {selected.state} · {selected.pincode}</b></article><article><small>IDENTITY METHOD</small><b>{selected.idType}</b></article></div>
        <div className="admin-privacy-note"><i>◇</i><p><b>Verification boundary</b><small>This dashboard stores masked review metadata only. Complete source-document and sanctions checks in the approved provider before attesting below.</small></p></div>
        <section className="admin-checks"><header><span>MANDATORY REVIEW CHECKS</span><b>{approvalChecks.filter(item=>checks.includes(item.id)).length}/{approvalChecks.length} complete</b></header><div>{approvalChecks.map(item=><label key={item.id} className={checks.includes(item.id)?"done":""}><input type="checkbox" checked={checks.includes(item.id)} onChange={()=>toggle(item.id)}/><i>{checks.includes(item.id)?"✓":""}</i><span>{item.label}</span></label>)}</div></section>
        <div className="admin-decision-fields"><label>Client risk rating<select value={riskLevel} onChange={event=>setRiskLevel(event.target.value)}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High · enhanced review</option></select></label><label>Decision note<textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="Required for re-upload or rejection; include a concise client-safe reason."/></label></div>
        {error?<p className="admin-error" role="alert">{error}</p>:null}{message?<p className="admin-message">✓ {message}</p>:null}<footer><button disabled={saving} onClick={()=>void decide("rejected")}>Reject</button><button disabled={saving} onClick={()=>void decide("action_required")}>Request re-upload</button><button className="approve" disabled={saving||approvalChecks.some(item=>!checks.includes(item.id))||(riskLevel==="high"&&note.trim().length<20)} onClick={()=>void decide("approved")}>{saving?"Recording…":"Approve KYC"} <b>→</b></button></footer>
        <section className="admin-audit"><header><span>AUDIT TRAIL</span><b>{selectedEvents.length} decisions</b></header>{selectedEvents.length?selectedEvents.map(item=><article key={item.id}><i>✓</i><div><b>{item.action.replace("_"," ")}</b><p>{item.note||"Mandatory checks completed."}</p><small>{item.actorEmail} · {new Date(item.createdAt).toLocaleString("en-IN")}</small></div></article>):<p>No reviewer decision has been recorded yet.</p>}</section>
      </section>:<section className="admin-kyc-loading">Select an application to begin review.</section>}
    </div>}
    <footer className="admin-kyc-footer">Internal compliance workspace · Never approve from screenshots or user-supplied claims alone.</footer>
  </main>;
}
