"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";

type Evidence={id:string;category:string;title:string;reference:string;issuer:string;status:string;documentDate:number|null;expiresAt:number|null;note:string|null;addedBy:string;createdAt:number;updatedAt:number};
const categories=[{id:"legal",label:"Legal classification"},{id:"fiu",label:"FIU registration"},{id:"aml",label:"AML & sanctions"},{id:"security",label:"Security assurance"},{id:"operations",label:"Custody, tax & operations"}];
const initial={category:"legal",title:"",reference:"",issuer:"",status:"recorded",documentDate:"",expiresAt:"",note:""};

export default function ComplianceEvidenceClient({reviewerEmail}:{reviewerEmail:string}){
 const [evidence,setEvidence]=useState<Evidence[]>([]),[form,setForm]=useState(initial),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[now]=useState(()=>Date.now());
 const load=useCallback(async()=>{setError("");try{const response=await fetch("/api/admin/compliance-evidence",{cache:"no-store"}),body=await response.json();if(!response.ok)throw new Error(body.error||"Evidence register unavailable");setEvidence(body.evidence)}catch(reason){setError(reason instanceof Error?reason.message:"Evidence register unavailable")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const update=(key:keyof typeof form,value:string)=>setForm(current=>({...current,[key]:value}));
 const save=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setError("");setMessage("");try{const response=await fetch("/api/admin/compliance-evidence",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}),body=await response.json();if(!response.ok)throw new Error(body.error||"Evidence could not be saved");setForm(initial);setMessage("Evidence reference recorded.");await load()}catch(reason){setError(reason instanceof Error?reason.message:"Evidence could not be saved")}finally{setSaving(false)}};
 const reviewed=evidence.filter(item=>item.status==="reviewed"&&(!item.expiresAt||item.expiresAt>now)).length;
 return <main className="admin-kyc-shell evidence-shell"><header className="admin-kyc-top"><a href="/"><img src="/chatonyou-logo.png" alt="ChatOnYou"/><b>TRADE</b></a><span>NEOCRAFT LLP · COMPLIANCE EVIDENCE</span><div><small>Authorised reviewer</small><b>{reviewerEmail}</b><a href="/admin/launch-review">Launch review</a><a href="/logout">Sign out</a></div></header>
  <section className="evidence-hero"><div><span>CONTROLLED REFERENCE REGISTER</span><h1>Track proof, not files.</h1><p>Store references to signed evidence held in your controlled document system. Do not paste PAN, Aadhaar, API keys, legal opinions or document contents here.</p></div><article><small>CURRENTLY REVIEWED</small><b>{reviewed}</b><em>{evidence.length} total references</em></article></section>
  <section className="evidence-layout"><form onSubmit={save} className="evidence-form"><header><span>ADD EVIDENCE REFERENCE</span><b>Metadata only</b></header><div className="evidence-fields"><label>Category<select value={form.category} onChange={event=>update("category",event.target.value)}>{categories.map(item=><option value={item.id} key={item.id}>{item.label}</option>)}</select></label><label>Review state<select value={form.status} onChange={event=>update("status",event.target.value)}><option value="recorded">Recorded · not reviewed</option><option value="reviewed">Reviewed · evidence checked</option><option value="expired">Expired</option><option value="superseded">Superseded</option></select></label><label className="wide">Evidence title<input required value={form.title} onChange={event=>update("title",event.target.value)} placeholder="Example: External VDA classification opinion"/></label><label>Controlled reference<input required value={form.reference} onChange={event=>update("reference",event.target.value)} placeholder="DMS reference only"/></label><label>Issuer / reviewer<input required value={form.issuer} onChange={event=>update("issuer",event.target.value)} placeholder="Firm, authority or auditor"/></label><label>Document date<input type="date" value={form.documentDate} onChange={event=>update("documentDate",event.target.value)}/></label><label>Expiry / renewal date<input type="date" value={form.expiresAt} onChange={event=>update("expiresAt",event.target.value)}/></label><label className="wide">Review note<textarea value={form.note} onChange={event=>update("note",event.target.value)} placeholder="For Reviewed status, record what was checked and by whom. Never paste document contents."/></label></div>{error?<p className="admin-error" role="alert">{error}</p>:null}{message?<p className="admin-message">✓ {message}</p>:null}<footer><small>Saving this reference does not grant regulatory approval.</small><button disabled={saving}>{saving?"Saving…":"Save evidence reference"} <b>→</b></button></footer></form>
  <section className="evidence-register"><header><span>EVIDENCE REGISTER</span><button onClick={()=>void load()}>Refresh</button></header>{loading?<p className="evidence-empty">Loading protected register…</p>:evidence.length?evidence.map(item=>{const expired=Boolean(item.expiresAt&&item.expiresAt<=now);return <article key={item.id}><i className={item.status==="reviewed"&&!expired?"ready":"pending"}>{item.status==="reviewed"&&!expired?"✓":"◇"}</i><div><header><b>{item.title}</b><em>{expired?"expired":item.status}</em></header><p>{categories.find(category=>category.id===item.category)?.label} · {item.issuer}</p><small>{item.reference} · recorded by {item.addedBy}</small>{item.note?<blockquote>{item.note}</blockquote>:null}</div></article>}):<p className="evidence-empty">No references recorded yet.</p>}</section></section>
  <footer className="admin-kyc-footer">Metadata register only · Original signed evidence must remain in NEOCRAFT LLP’s controlled document system.</footer>
 </main>
}
