"use client";

import { useEffect, useState } from "react";

type Decision={id:string;asset:string;decision:"BUY"|"SELL"|"NO TRADE";confidence:number;reasons:string[];indicators:{ema9:number;ema21:number;rsi14:number;macd:number;macdSignal:number;atr14:number;volumeRatio:number};entryPrice:number;stopPrice:number|null;targetPrice:number|null;createdAt:number};
const usd=(value:number|null)=>value===null?"—":`$${new Intl.NumberFormat("en-US",{maximumFractionDigits:4}).format(value)}`;

export default function DecisionAudit(){
 const [item,setItem]=useState<Decision|null>(null),[threshold,setThreshold]=useState(80),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get("id");if(!id){setError("Decision link is missing");setLoading(false);return}Promise.all([fetch(`/api/decisions?id=${encodeURIComponent(id)}`,{cache:"no-store"}),fetch("/api/account",{cache:"no-store"})]).then(async([decisionResponse,accountResponse])=>{const decisionData=await decisionResponse.json();if(!decisionResponse.ok)throw new Error(decisionData.error||"Decision could not be loaded");setItem(decisionData.decision);if(accountResponse.ok){const account=await accountResponse.json();setThreshold(Number(account.settings?.minConfidence)||80)}}).catch(reason=>setError(reason instanceof Error?reason.message:"Decision could not be loaded")).finally(()=>setLoading(false))},[]);
 if(loading)return <main className="decision-audit-shell"><section className="decision-audit-main"><div className="notification-empty"><i>…</i><h2>Loading saved decision</h2></div></section></main>;
 if(!item)return <main className="decision-audit-shell"><section className="decision-audit-main"><div className="notification-empty"><i>!</i><h2>Decision unavailable</h2><p>{error}</p><a href="/trade/notifications">Back to alert inbox</a></div></section></main>;
 const eligible=item.decision!=="NO TRADE"&&item.confidence>=threshold&&item.stopPrice!==null&&item.targetPrice!==null;
 const features=[{name:"EMA trend",value:item.indicators.ema9>item.indicators.ema21?"Bullish":"Bearish",note:`EMA 9 ${item.indicators.ema9>item.indicators.ema21?"above":"below"} EMA 21.`},{name:"RSI 14",value:String(item.indicators.rsi14),note:"Momentum reading from the saved candle set."},{name:"MACD",value:String(item.indicators.macd),note:`Signal line ${item.indicators.macdSignal}.`},{name:"Volume",value:`${item.indicators.volumeRatio}×`,note:"Ratio versus the recent volume average."},{name:"ATR 14",value:String(item.indicators.atr14),note:"Saved volatility measurement."}];
 return <main className="decision-audit-shell"><header className="decision-top"><a className="terminal-logo" href="/"><img src="/chatonyou-logo.png" alt="ChatOnYou"/><b>TRADE</b></a><div><span>Saved AI Decision</span><b>{new Date(item.createdAt).toLocaleString("en-IN")}</b></div><a href="/trade/notifications">×</a></header><section className="decision-audit-main">
  <div className="decision-breadcrumb"><a href="/trade/notifications">Alert inbox</a><span>›</span><b>{item.asset} decision</b></div>
  <header className="decision-hero"><div><span>DECISION ID · {item.id}</span><h1>{eligible?`Review ${item.decision} opportunity.`:"Capital remains protected."}</h1><p>{item.reasons.join(" · ")}</p></div><div className={`decision-result ${item.decision.toLowerCase().replace(" ","-")}`}><span>SAVED DECISION</span><strong>{item.decision}</strong><div><b>{item.confidence}%</b><small>quant confidence</small></div><i><em style={{width:item.confidence+"%"}}/></i></div></header>
  <section className="decision-market-strip"><div><i>{item.asset[0]}</i><span><b>{item.asset}/USDT</b><small>Binance public candles</small></span></div><span>Saved price<b>{usd(item.entryPrice)}</b></span><span>Required confidence<b>{threshold}%</b></span><span>Alert mode<b>Paper only</b></span><span>Order status<b>{eligible?"Ready to re-check":"Not prepared"}</b></span></section>
  <div className="decision-audit-grid"><section className="feature-engine-card"><header><div><span>01 · SAVED FEATURES</span><h2>What the scanner measured</h2></div><em>{features.length} inputs</em></header><div>{features.map(feature=><button key={feature.name}><span><b>{feature.name}</b><small>{feature.note}</small></span><strong>{feature.value}</strong></button>)}</div><footer><span>QUANT CONFIDENCE</span><strong>{item.confidence}<small>/ 100</small></strong><i><em style={{width:item.confidence+"%"}}/></i><p>This audit is saved evidence, not a current execution price.</p></footer></section>
   <aside className="decision-right-column"><section className="risk-gate-card"><header><div><span>02 · REVIEW GATE</span><h2>{eligible?"Eligible for fresh validation":"Order blocked safely"}</h2></div><i className={eligible?"passed":"blocked"}>{eligible?"✓":"!"}</i></header><div><article><i className={item.confidence>=threshold?"pass":"block"}>{item.confidence>=threshold?"✓":"×"}</i><span><b>Confidence ≥ {threshold}%</b><small>{item.confidence}% saved confidence</small></span></article><article><i className={item.stopPrice!==null?"pass":"block"}>{item.stopPrice!==null?"✓":"×"}</i><span><b>Protective levels</b><small>Stop-loss and target must both exist.</small></span></article><article><i className="wait">…</i><span><b>Fresh market validation</b><small>The order screen reloads the live signal before enabling confirmation.</small></span></article></div></section>
   <section className="decision-level-card"><header><span>03 · SAVED PARAMETERS</span><b>{eligible?"REVIEW":"BLOCKED"}</b></header><div><span>Entry<b>{usd(item.entryPrice)}</b></span><span>Stop loss<b>{usd(item.stopPrice)}</b></span><span>Take profit<b>{usd(item.targetPrice)}</b></span><span>Execution<b>Manual paper</b></span></div>{eligible?<a href={`/trade/order?asset=${item.asset}&side=${item.decision}&amount=500`}>Re-check &amp; prepare paper order <span>→</span></a>:<p><i>◇</i>No order can be prepared from this saved decision.</p>}</section></aside>
  </div><section className="decision-explanation"><i>✦</i><div><span>IMPORTANT</span><h2>A saved alert is not a live instruction.</h2><p>The order screen fetches current candles again, verifies direction, confidence, stop-loss, target and account limits, then requires your manual paper confirmation.</p></div></section><footer className="decision-footer"><a href="/trade/notifications">← Back to alert inbox</a><span>Paper-trading audit · Not investment advice</span><a href="/trade/ai">Open AI activity →</a></footer>
 </section></main>
}
