"use client";

import { useEffect,useState } from "react";

type Decision={coin:string,name:string,symbol:string,color:string,price:string,change:string,type:"BUY"|"SELL"|"NO TRADE",confidence:number,time:string,summary:string,threshold:number,features:{name:string,value:string,score:number,tone:string,note:string}[],checks:{name:string,status:"pass"|"block"|"wait",detail:string}[],levels:{entry:string,stop:string,target:string,risk:string}};
const records:Record<string,Decision>={
 BTC:{coin:"BTC",name:"Bitcoin",symbol:"₿",color:"#f5a623",price:"$113,240.80",change:"+2.84%",type:"NO TRADE",confidence:64,time:"12:42",summary:"Trend is constructive, but resistance confirmation and minimum confidence are still missing.",threshold:80,features:[{name:"EMA trend",value:"Bullish",score:82,tone:"good",note:"EMA 9 remains above EMA 21."},{name:"RSI 14",value:"63.4",score:68,tone:"good",note:"Healthy momentum, not overbought."},{name:"Volume",value:"+12%",score:59,tone:"wait",note:"Below breakout confirmation level."},{name:"Order book",value:"+4% buy",score:54,tone:"wait",note:"Pressure is positive but not decisive."},{name:"Volatility",value:"Normal",score:75,tone:"good",note:"ATR remains inside allowed range."},{name:"Resistance",value:"Unconfirmed",score:31,tone:"bad",note:"Price has not closed above $113,500."}],checks:[{name:"Confidence ≥ 80%",status:"block",detail:"64% does not meet the configured threshold."},{name:"Stop-loss available",status:"pass",detail:"A valid protective stop can be placed."},{name:"Daily loss limit",status:"pass",detail:"0.8% of 3% daily risk is currently used."},{name:"Open position capacity",status:"pass",detail:"1 of 2 permitted positions is open."},{name:"Abnormal volatility",status:"pass",detail:"No volatility pause is active."}],levels:{entry:"Waiting",stop:"—",target:"—",risk:"0%"}},
 SOL:{coin:"SOL",name:"Solana",symbol:"S",color:"#92ffc7",price:"$182.44",change:"+4.21%",type:"BUY",confidence:84,time:"11:18",summary:"Resistance breakout, volume expansion and bullish momentum created an eligible controlled entry.",threshold:80,features:[{name:"EMA trend",value:"Bullish",score:91,tone:"good",note:"EMA structure is aligned upward."},{name:"RSI 14",value:"61.8",score:79,tone:"good",note:"Momentum remains healthy."},{name:"Volume",value:"+38%",score:93,tone:"good",note:"Breakout volume is above average."},{name:"Order book",value:"+17% buy",score:82,tone:"good",note:"Buyer pressure supports the move."},{name:"Volatility",value:"Normal",score:74,tone:"good",note:"ATR is inside the permitted range."},{name:"Resistance",value:"Confirmed",score:88,tone:"good",note:"Candle closed above $181.90."}],checks:[{name:"Confidence ≥ 80%",status:"pass",detail:"84% meets the configured threshold."},{name:"Stop-loss available",status:"pass",detail:"Protective stop prepared at $178.80."},{name:"Daily loss limit",status:"pass",detail:"Trade risk stays below the 3% daily limit."},{name:"Open position capacity",status:"pass",detail:"1 of 2 permitted positions is open."},{name:"Abnormal volatility",status:"pass",detail:"No volatility pause is active."}],levels:{entry:"$182.44",stop:"$178.80",target:"$189.20",risk:"0.8%"}},
 ETH:{coin:"ETH",name:"Ethereum",symbol:"◆",color:"#8293ff",price:"$4,216.12",change:"-0.76%",type:"SELL",confidence:81,time:"09:54",summary:"Momentum weakened below support while sell-side pressure increased enough to pass the signal rule.",threshold:80,features:[{name:"EMA trend",value:"Bearish",score:84,tone:"bad",note:"Fast EMA crossed below slow EMA."},{name:"RSI 14",value:"41.2",score:77,tone:"bad",note:"Momentum is weakening."},{name:"Volume",value:"+21% sell",score:85,tone:"bad",note:"Sell volume expanded below support."},{name:"Order book",value:"-13% buy",score:80,tone:"bad",note:"Offers outweigh bids."},{name:"Volatility",value:"Normal",score:72,tone:"good",note:"ATR is inside allowed range."},{name:"Support",value:"Broken",score:87,tone:"bad",note:"Price closed below $4,230."}],checks:[{name:"Confidence ≥ 80%",status:"pass",detail:"81% meets the configured threshold."},{name:"Stop-loss available",status:"pass",detail:"Protective stop prepared at $4,268."},{name:"Daily loss limit",status:"pass",detail:"Trade risk stays below the 3% daily limit."},{name:"Open position capacity",status:"pass",detail:"Capacity is available."},{name:"Abnormal volatility",status:"pass",detail:"No volatility pause is active."}],levels:{entry:"$4,216",stop:"$4,268",target:"$4,108",risk:"0.8%"}},
};

export default function DecisionAudit(){
 const [coin,setCoin]=useState("BTC"),[expanded,setExpanded]=useState<string|null>(null);
 useEffect(()=>{const value=(new URLSearchParams(window.location.search).get("coin")||"BTC").toUpperCase();setCoin(records[value]?value:"BTC")},[]);
 const d=records[coin]||records.BTC,isBlocked=d.type==="NO TRADE";
 return <main className="decision-audit-shell">
  <header className="decision-top"><a className="terminal-logo" href="/"><img src="/chatonyou-logo.png" alt="ChatOnYou"/><b>TRADE</b></a><div><span>AI Decision Audit</span><b>{d.time} · Today</b></div><a href="/trade/ai">×</a></header>
  <section className="decision-audit-main">
   <div className="decision-breadcrumb"><a href="/trade/ai">AI activity</a><span>›</span><b>{d.coin} decision · {d.time}</b></div>
   <header className="decision-hero"><div><span>DECISION ID · CY-AI-{d.coin}-0821-{d.time.replace(":","")}</span><h1>{isBlocked?"AI protected capital.":`AI chose ${d.type}.`}</h1><p>{d.summary}</p></div><div className={`decision-result ${d.type.toLowerCase().replace(" ","-")}`}><span>FINAL DECISION</span><strong>{d.type}</strong><div><b>{d.confidence}%</b><small>AI confidence</small></div><i><em style={{width:d.confidence+"%"}}/></i></div></header>
   <section className="decision-market-strip"><div><i style={{background:d.color}}>{d.symbol}</i><span><b>{d.coin}/USDT</b><small>{d.name} · Spot</small></span></div><span>Demo price<b>{d.price}</b></span><span>24H change<b className={d.change.startsWith("+")?"up":"down"}>{d.change}</b></span><span>Required confidence<b>{d.threshold}%</b></span><span>Decision time<b>{d.time}:18 IST</b></span></section>
   <div className="decision-audit-grid">
    <section className="feature-engine-card"><header><div><span>01 · FEATURE ENGINE</span><h2>What the market showed</h2></div><em>6 inputs</em></header><div>{d.features.map(f=><button onClick={()=>setExpanded(expanded===f.name?null:f.name)} className={expanded===f.name?"expanded":""} key={f.name}><span><b>{f.name}</b><small>{f.note}</small></span><strong className={f.tone}>{f.value}</strong><div><i><em className={f.tone} style={{width:f.score+"%"}}/></i><b>{f.score}</b></div><em>{expanded===f.name?"−":"+"}</em></button>)}</div><footer><span>COMBINED QUANT SCORE</span><strong>{d.confidence}<small>/ 100</small></strong><i><em style={{width:d.confidence+"%"}}/></i><p>Indicator scores are deterministic demo calculations. The explanation layer does not place orders.</p></footer></section>
    <aside className="decision-right-column">
     <section className="risk-gate-card"><header><div><span>02 · RISK ENGINE</span><h2>{isBlocked?"Order blocked safely":"All checks passed"}</h2></div><i className={isBlocked?"blocked":"passed"}>{isBlocked?"!":"✓"}</i></header><div>{d.checks.map(c=><article key={c.name}><i className={c.status}>{c.status==="pass"?"✓":c.status==="block"?"×":"…"}</i><span><b>{c.name}</b><small>{c.detail}</small></span></article>)}</div></section>
     <section className="decision-level-card"><header><span>03 · ORDER PARAMETERS</span><b>{isBlocked?"NOT CREATED":"PREPARED"}</b></header><div><span>Entry<b>{d.levels.entry}</b></span><span>Stop loss<b>{d.levels.stop}</b></span><span>Take profit<b>{d.levels.target}</b></span><span>Capital risk<b>{d.levels.risk}</b></span></div>{isBlocked?<p><i>◇</i>No paper order was created. AI will re-check after the next candle closes.</p>:<a href={`/trade/order?asset=${d.coin}&side=${d.type}&amount=500`}>Review prepared paper order <span>→</span></a>}</section>
    </aside>
   </div>
   <section className="decision-timeline"><header><span>DECISION PIPELINE</span><b>Completed in 284 ms · Demo</b></header><div><article className="done"><i>✓</i><span><b>Market snapshot</b><small>Price, candle, volume, order book</small></span><em>0 ms</em></article><b/><article className="done"><i>✓</i><span><b>Feature calculation</b><small>EMA, RSI, ATR and structure</small></span><em>72 ms</em></article><b/><article className="done"><i>✓</i><span><b>Signal score</b><small>{d.confidence}% confidence generated</small></span><em>164 ms</em></article><b/><article className={isBlocked?"blocked":"done"}><i>{isBlocked?"×":"✓"}</i><span><b>Risk validation</b><small>{isBlocked?"Confidence rule blocked order":"Every hard rule passed"}</small></span><em>231 ms</em></article><b/><article className={isBlocked?"idle":"done"}><i>{isBlocked?"—":"✓"}</i><span><b>Paper order</b><small>{isBlocked?"No order created":"Parameters prepared"}</small></span><em>284 ms</em></article></div></section>
   <section className="decision-explanation"><i>✦</i><div><span>PLAIN-LANGUAGE EXPLANATION</span><h2>{isBlocked?"Why did AI choose NO TRADE?":`Why did AI choose ${d.type}?`}</h2><p>{isBlocked?"BTC had a bullish trend, but trend alone was not enough. Volume confirmation was weak and resistance had not broken. Because confidence stayed at 64%—below your 80% rule—the risk engine stopped the order. Waiting protected the paper balance from an uncertain entry.":`${d.coin} passed the trend, momentum and volume tests. Confidence reached ${d.confidence}%, above your ${d.threshold}% rule, and every risk check passed. The deterministic engine prepared entry, stop-loss and take-profit before allowing the simulated ${d.type.toLowerCase()} order.`}</p></div></section>
   <footer className="decision-footer"><a href="/trade/ai">← Back to AI activity</a><span>Illustrative paper-trading audit · Not investment advice</span><a href={`/trade/markets`}>Open market scanner →</a></footer>
  </section>
 </main>
}
