"use client";
import { useEffect,useMemo,useState } from "react";

type Asset={coin:string,name:string,symbol:string,color:string,amount:string,price:string,value:number,share:number,change:string,pnl:string,cost:string};
const assets:Asset[]=[
 {coin:"USDT",name:"Tether",symbol:"₮",color:"#58d6a0",amount:"87.16",price:"₹83.58",value:7284,share:67,change:"+0.02%",pnl:"+₹1.40",cost:"₹7,282"},
 {coin:"BTC",name:"Bitcoin",symbol:"₿",color:"#f5a623",amount:"0.0142",price:"₹94,84,500",value:1347,share:12,change:"+2.84%",pnl:"+₹94.60",cost:"₹1,252"},
 {coin:"ETH",name:"Ethereum",symbol:"◆",color:"#8293ff",amount:"0.184",price:"₹3,51,740",value:647,share:6,change:"+1.62%",pnl:"+₹61.20",cost:"₹586"},
 {coin:"SOL",name:"Solana",symbol:"S",color:"#92ffc7",amount:"1.68",price:"₹15,980",value:2684,share:15,change:"+4.12%",pnl:"+₹118.40",cost:"₹2,566"},
];
type Position={id:string;coin:string;side:string;entry:string;current:string;size:string;pnl:string;percent:string;stop:string;target:string;mode:string;pnlPositive:boolean};
const activity=[
 {icon:"↘",title:"Paper BUY · SOL",time:"Today · 11:18",amount:"+2.80 SOL",value:"₹42,000"},
 {icon:"↗",title:"Paper SELL · ETH",time:"Today · 09:54",amount:"-0.12 ETH",value:"₹42,160"},
 {icon:"+",title:"P&L settled · BTC",time:"Yesterday",amount:"+₹94.60",value:"Closed"},
];

export default function Portfolio(){
 const [tab,setTab]=useState("Overview"),[selected,setSelected]=useState<Asset|null>(null),[openPositions,setOpenPositions]=useState<Position[]>([]),[balance,setBalance]=useState(10000),[toast,setToast]=useState("");
 const total=useMemo(()=>assets.reduce((sum,item)=>sum+item.value,0),[]);
 useEffect(()=>{
  let active=true;
  const sync=()=>fetch("/api/trades",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"sync"}),cache:"no-store"}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||"Position sync failed");if(!active)return;setBalance((data.balancePaise||0)/100);const saved:Position[]=(data.trades||[]).filter((item:{status:string})=>item.status==="open").map((item:{id:string;asset:string;side:string;entryPrice:number;amountPaise:number;stopPrice:number;targetPrice:number})=>{const mark=Number(data.marks?.[item.asset]?.price||item.entryPrice),direction=item.side==="SELL"?-1:1,pnlPaise=Math.max(-item.amountPaise,Math.round(item.amountPaise*((mark-item.entryPrice)/item.entryPrice)*direction)),percent=((mark-item.entryPrice)/item.entryPrice)*100*direction;return{id:item.id,coin:item.asset+"/USDT",side:item.side,entry:"$"+item.entryPrice.toLocaleString("en-US"),current:"$"+mark.toLocaleString("en-US"),size:"₹"+(item.amountPaise/100).toLocaleString("en-IN"),pnl:(pnlPaise>=0?"+":"-")+"₹"+Math.abs(pnlPaise/100).toFixed(2),percent:(percent>=0?"+":"")+percent.toFixed(2)+"%",stop:"$"+item.stopPrice.toLocaleString("en-US"),target:"$"+item.targetPrice.toLocaleString("en-US"),mode:"Saved paper",pnlPositive:pnlPaise>=0}});setOpenPositions(saved);if(data.closed?.length)setToast(`${data.closed.length} paper position${data.closed.length>1?"s":""} closed by saved protection`)}).catch(reason=>{if(active)setToast(reason instanceof Error?reason.message:"Could not sync saved paper positions")});
  sync();const timer=window.setInterval(sync,30000);return()=>{active=false;window.clearInterval(timer)};
 },[]);
 const exportPortfolio=()=>{const rows=[["Type","Asset","Side","Size","Entry","Stop","Target"],...assets.map(item=>["Holding",item.coin,"",item.value.toString(),item.cost,"",""]),...openPositions.map(item=>["Open position",item.coin,item.side,item.size,item.entry,item.stop,item.target])];const csv=rows.map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(",")).join("\n"),url=URL.createObjectURL(new Blob([csv],{type:"text/csv"})),link=document.createElement("a");link.href=url;link.download="chatonyou-paper-portfolio.csv";link.click();URL.revokeObjectURL(url);setToast("Paper portfolio exported")};
 return <main className="portfolio-shell">
  <header className="ai-dash-top"><a className="terminal-logo" href="/"><img src="/chatonyou-logo.png" alt="ChatOnYou"/><b>TRADE</b></a><div className="ai-dash-title"><b>Portfolio</b><span><i/> Paper assets</span></div><div className="ai-dash-actions"><button><small>SAVED PAPER BALANCE</small><b>₹{balance.toLocaleString("en-IN",{minimumFractionDigits:2})}</b></button><a href="/trade/profile">NS</a></div></header>
  <div className="ai-dash-layout"><aside className="ai-dash-nav"><div><a href="/trade"><i>↗</i><span>Trade</span></a><a href="/trade/ai"><i>✦</i><span>AI Trader</span></a><a href="/trade/bots"><i>◉</i><span>Bots</span></a><a href="/trade/wallet"><i>W</i><span>Wallet</span></a><a className="active" href="/trade/portfolio"><i>◒</i><span>Portfolio</span></a><a href="/trade/history"><i>H</i><span>History</span></a><a href="/trade/analytics"><i>⌁</i><span>Analytics</span></a><a href="/trade/backtest"><i>◫</i><span>Backtest</span></a></div><a href="/trade/settings"><i>⚙</i><span>Settings</span></a></aside>
   <section className="portfolio-main">
    <div className="portfolio-head"><div><span>PAPER PORTFOLIO</span><h1>Your crypto, clearly.</h1><p>Track allocation, open positions and simulated performance.</p></div><div><a href="/trade">+ New paper trade</a><button onClick={exportPortfolio}>⇩ Export</button></div></div>
    <div className="portfolio-tabs">{["Overview","Holdings","Open positions"].map(item=><button className={tab===item?"active":""} onClick={()=>setTab(item)} key={item}>{item}{item==="Open positions"&&<i>{openPositions.length}</i>}</button>)}</div>
    {tab==="Overview"&&<>
     <section className="portfolio-overview">
      <article className="portfolio-value"><header><span>TOTAL PAPER VALUE</span><i>DEMO</i></header><strong>₹{total.toLocaleString("en-IN")}.00</strong><p>≈ $143.12 virtual portfolio</p><div className="portfolio-gain"><b>+₹274.20</b><span>+2.59% today</span></div><div className="portfolio-line"><div/><i/><b>+8.42%</b></div><footer><span>22 Jul</span><span>01 Aug</span><span>10 Aug</span><span>Today</span></footer></article>
      <article className="portfolio-allocation"><header><span>ALLOCATION</span><a href="#" onClick={e=>{e.preventDefault();setTab("Holdings")}}>View assets →</a></header><div className="portfolio-ring"><div><strong>4</strong><small>assets</small></div></div><div className="portfolio-legend">{assets.map(item=><span key={item.coin}><i style={{background:item.color}}/><b>{item.coin}</b><em>{item.share}%</em></span>)}</div></article>
      <article className="portfolio-summary"><header><span>PERFORMANCE</span><i>30D</i></header><div><span>Unrealized P&amp;L<b className="portfolio-positive">+₹213.00</b></span><span>Realized P&amp;L<b className="portfolio-positive">+₹629.00</b></span><span>Best asset<b>SOL <em>+4.12%</em></b></span><span>Open risk<b>0.8%</b></span></div><a href="/trade/analytics">Full analytics →</a></article>
     </section>
     <section className="portfolio-open"><header><div><h2>Open positions</h2><p>Live marks refresh every 30 seconds; saved stops and targets settle during each refresh.</p></div><button onClick={()=>setTab("Open positions")}>View all</button></header>{openPositions.length?<div className="position-list"><div className="position-labels"><span>MARKET</span><span>MODE</span><span>ENTRY</span><span>CURRENT</span><span>SIZE</span><span>UNREALIZED P&amp;L</span><span>PROTECTION</span><span/></div>{openPositions.map(item=><div key={item.id}><strong>{item.coin}<small>{item.side} · Spot</small></strong><span>{item.mode}</span><span>{item.entry}</span><b>{item.current}</b><span>{item.size}</span><strong className={item.pnlPositive?"portfolio-positive":"history-negative"}>{item.pnl}<small>{item.percent}</small></strong><span><i>SL</i> {item.stop}<small><i>TP</i> {item.target}</small></span><button onClick={()=>window.location.href=`/trade/exit?id=${encodeURIComponent(item.id)}`}>Close</button></div>)}</div>:<div className="positions-empty">✓ All saved paper positions are closed.</div>}</section>
     <div className="portfolio-bottom"><section className="portfolio-assets"><header><div><h2>Top holdings</h2><p>Click an asset for a detailed view.</p></div><button onClick={()=>setTab("Holdings")}>All assets</button></header><div>{assets.slice(0,3).map(item=><button onClick={()=>setSelected(item)} key={item.coin}><i style={{background:item.color}}>{item.symbol}</i><span><b>{item.coin}</b><small>{item.name}</small></span><span><b>{item.amount}</b><small>{item.price}</small></span><strong>₹{item.value.toLocaleString("en-IN")}<small>{item.share}% allocation</small></strong><em>{item.change}</em><b>›</b></button>)}</div></section><section className="portfolio-activity"><header><h2>Recent activity</h2><a href="/trade/history">History →</a></header><div>{activity.map(item=><article key={item.title}><i>{item.icon}</i><span><b>{item.title}</b><small>{item.time}</small></span><span><b>{item.amount}</b><small>{item.value}</small></span></article>)}</div></section></div>
    </>}
    {tab==="Holdings"&&<section className="all-holdings"><header><div><h2>All paper holdings</h2><p>Virtual balances created by simulated activity.</p></div><span>₹{total.toLocaleString("en-IN")} total</span></header><div className="holding-labels"><span>ASSET</span><span>BALANCE</span><span>PRICE</span><span>VALUE</span><span>ALLOCATION</span><span>24H</span><span>P&amp;L</span><span/></div>{assets.map(item=><button onClick={()=>setSelected(item)} key={item.coin}><span className="holding-name"><i style={{background:item.color}}>{item.symbol}</i><b>{item.coin}<small>{item.name}</small></b></span><span>{item.amount}</span><span>{item.price}</span><b>₹{item.value.toLocaleString("en-IN")}</b><span className="holding-share"><i><b style={{width:item.share+"%",background:item.color}}/></i>{item.share}%</span><em>{item.change}</em><strong>{item.pnl}</strong><i>›</i></button>)}</section>}
    {tab==="Open positions"&&<section className="all-positions"><header><div><h2>Open paper positions</h2><p>Server-checked marks, stop-loss and take-profit refresh every 30 seconds while this page is open.</p></div><span>{openPositions.length} active</span></header>{openPositions.length?<div>{openPositions.map(item=><article key={item.id}><header><strong>{item.coin}<small>{item.mode} · Spot {item.side}</small></strong><em>{item.percent}</em></header><div><span>Entry<b>{item.entry}</b></span><span>Current<b>{item.current}</b></span><span>Position size<b>{item.size}</b></span><span>Unrealized P&amp;L<b className={item.pnlPositive?"portfolio-positive":"history-negative"}>{item.pnl}</b></span></div><footer><span><i>SL</i>{item.stop}</span><span><i>TP</i>{item.target}</span><button onClick={()=>window.location.href=`/trade/exit?id=${encodeURIComponent(item.id)}`}>Close paper position</button></footer></article>)}</div>:<div className="large-position-empty"><i>✓</i><h2>No open positions</h2><p>All simulated positions have been safely closed.</p><a href="/trade">Open trading terminal →</a></div>}</section>}
    <p className="ai-data-note">Paper portfolio only · Values are illustrative · No real assets or funds are held</p>
   </section>
  </div>
  {selected&&<div className="asset-drawer-bg" onClick={()=>setSelected(null)}><aside className="asset-drawer" onClick={e=>e.stopPropagation()}><header><div className="asset-drawer-name"><i style={{background:selected.color}}>{selected.symbol}</i><span><b>{selected.coin}</b><small>{selected.name}</small></span></div><button onClick={()=>setSelected(null)}>×</button></header><section className="asset-price"><span>CURRENT PAPER VALUE</span><strong>₹{selected.value.toLocaleString("en-IN")}</strong><b>{selected.change} today</b><div><i/><i/><i/><i/></div></section><div className="asset-details"><span>Virtual amount<b>{selected.amount} {selected.coin}</b></span><span>Current price<b>{selected.price}</b></span><span>Average cost<b>{selected.cost}</b></span><span>Paper P&amp;L<b className="portfolio-positive">{selected.pnl}</b></span><span>Portfolio share<b>{selected.share}%</b></span><span>Account type<b>Demo</b></span></div><section className="asset-ai-note"><span>✦ AI VIEW</span><h3>{selected.coin==="USDT"?"Capital available":"Position remains protected"}</h3><p>{selected.coin==="USDT"?"Virtual USDT is available for future paper opportunities.":"Current exposure remains inside the configured 1% risk-per-trade limit."}</p></section><div className="asset-actions"><a href="/trade">Trade {selected.coin}</a><button onClick={()=>setSelected(null)}>Close</button></div></aside></div>}
  {toast&&<div className="toast"><span>✓</span>{toast}</div>}
  <nav className="ai-mobile-nav"><a href="/trade"><i>↗</i>Trade</a><a href="/trade/ai"><i>✦</i>AI</a><a href="/trade/bots"><i>◉</i>Bots</a><a className="active" href="/trade/portfolio"><i>◒</i>Portfolio</a><a href="/trade/settings"><i>⚙</i>Settings</a></nav>
 </main>
}
