const readiness=[
 {icon:"◇",title:"Entity & governance",status:"Required before live",text:"FIU-IND registration, an India-based Principal Officer and a separate Designated Director must be in place.",items:["FINGate application and RE-ID","Board-approved AML/CFT/CPF policy","Annual risk assessment and independent audit"]},
 {icon:"◎",title:"Client due diligence",status:"Specification ready",text:"Live onboarding will require verified identity, contact, financial and device-level evidence.",items:["PAN plus accepted identity document","Liveness selfie, IP and geolocation","OTP contact checks and bank penny-drop"]},
 {icon:"⌁",title:"Transaction monitoring",status:"Live integration pending",text:"Every live transfer must be continuously monitored and reconstructable from its source to destination.",items:["Blockchain analytics and wallet screening","Alert review and STR escalation","Five-year tamper-resistant records"]},
 {icon:"↗",title:"Travel Rule",status:"Live integration pending",text:"Originator and beneficiary information must travel securely before or with every applicable VDA transfer.",items:["PAN, identity and verified address","Names and wallet/account addresses","No post-facto information submission"]},
 {icon:"✓",title:"Sanctions controls",status:"Required before transfer",text:"Screening must run during onboarding, KYC changes, list changes and every live VDA transaction.",items:["UNSC, UAPA and WMDA screening","Hold transfer until screening clears","Re-screen when sanctions lists change"]},
 {icon:"▣",title:"Cybersecurity & records",status:"Audit required",text:"A CERT-In empanelled audit must cover the complete environment used for notified VDA services.",items:["Wallet, API and cryptographic controls","Incident detection and reporting readiness","Backup, recovery and complete audit trails"]},
];
const guidelineControls=[
 {n:"01",title:"CDD and beneficial ownership",text:"Risk-based customer due diligence, beneficial-owner identification, enhanced checks and ongoing KYC updates."},
 {n:"02",title:"Monitoring and risk assessment",text:"Customer and transaction risk assessment, continuous monitoring, alert review and documented escalation."},
 {n:"03",title:"Travel Rule and records",text:"Secure originator and beneficiary information sharing, transaction traceability and five-year record retention."},
 {n:"04",title:"Reporting, sanctions and governance",text:"STR reporting, sanctions screening, Principal Officer oversight, staff training, audit and policy governance."},
];

export default function ComplianceReadiness(){
 return <main className="compliance-shell">
  <header className="compliance-top"><a href="/" className="compliance-logo"><img src="/chatonyou-logo.png" alt="ChatOnYou"/><b>TRADE</b></a><nav><a href="/terms">Policies</a><a href="/help">Help Center</a><a href="/">×</a></nav></header>
  <section className="compliance-hero"><div className="compliance-glow"/><span>FIU-IND READINESS · PAPER MODE</span><h1>Build compliance first.<br/><em>Enable live trading last.</em></h1><p>This workspace maps the operational controls required before ChatOnYou can consider real VDA exchange, transfer or custody services.</p><div><a href="/kyc">Open client KYC <b>↗</b></a><a href="#roadmap">Review readiness</a></div></section>
  <section className="compliance-status"><article><i>✓</i><span><small>CURRENT PRODUCT MODE</small><b>Paper trading only</b><p>No real funds, custody or blockchain transfers.</p></span></article><article className="warning"><i>!</i><span><small>FIU-IND STATUS</small><b>Guidelines recorded · Registration pending</b><p>AML/CFT VDA Guidelines updated 08 January 2026 are the readiness baseline. This is not FIU registration.</p></span></article><article><i>Ⅱ</i><span><small>LIVE EXECUTION</small><b>Disabled by design</b><p>Compliance, security and legal review must pass first.</p></span></article></section>
  <section className="compliance-roadmap" id="roadmap"><header><span>READINESS ROADMAP</span><h2>Six control systems before live.</h2><p>Each workstream needs documented ownership, tested technology and evidence that can be demonstrated to FIU-IND.</p></header><div>{readiness.map((item,index)=><article key={item.title}><header><i>{item.icon}</i><span>0{index+1}</span><em>{item.status}</em></header><h3>{item.title}</h3><p>{item.text}</p><ul>{item.items.map(point=><li key={point}><i>✓</i>{point}</li>)}</ul></article>)}</div></section>
  <section className="compliance-gates"><header><span>FIU-IND GUIDELINES · UPDATED 08 JANUARY 2026</span><h2>Guidelines added now. Registration follows separately.</h2></header><div>{guidelineControls.map(item=><article key={item.n}><span>{item.n}</span><b>{item.title}</b><p>{item.text}</p></article>)}</div></section>
  <section className="compliance-gates"><header><span>NON-NEGOTIABLE GATES</span><h2>Live stays locked until every gate clears.</h2></header><div><article><span>01</span><b>Legal classification</b><p>Confirm which proposed services are notified VDA activities under PMLA.</p></article><article><span>02</span><b>FIU registration</b><p>Complete documents, in-person systems demonstration and obtain formal RE-ID.</p></article><article><span>03</span><b>Independent assurance</b><p>Complete CERT-In cybersecurity audit and independent AML control review.</p></article><article><span>04</span><b>Controlled pilot</b><p>Test KYC, monitoring, Travel Rule, sanctions and incident response end to end.</p></article></div></section>
  <section className="compliance-boundary"><div><span>PRODUCT BOUNDARY</span><h2>What ChatOnYou can do now.</h2><ul><li><i>✓</i>Virtual ₹10,000 paper balance</li><li><i>✓</i>Illustrative AI decisions and risk checks</li><li><i>✓</i>Saved simulated orders and analytics</li></ul></div><div><span>WHAT REMAINS BLOCKED</span><h2>What waits for formal readiness.</h2><ul><li><i>×</i>Real deposits, withdrawals or custody</li><li><i>×</i>Live exchange order execution</li><li><i>×</i>Hosted-wallet VDA transfers</li></ul></div></section>
  <footer className="compliance-footer"><p>This is a product-readiness overview, not a claim of regulatory approval or legal advice.</p><div><a href="/risk-disclosure">Risk disclosure</a><a href="/privacy">Privacy</a><a href="/contact">Contact</a></div></footer>
 </main>
}
