"use client";

import { useState } from "react";

type Topic={id:string,icon:string,title:string,desc:string,question:string,answer:string,points:string[],action?:{label:string,href:string}};
const topics:Topic[]=[
 {id:"signal",icon:"✦",title:"AI Signal samjho",desc:"BUY, SELL aur NO TRADE",question:"AI signal ka simple matlab kya hai?",answer:"AI market ke trend, momentum, volume, order book aur volatility ko check karke teen decisions deta hai: BUY, SELL ya NO TRADE. Confidence percentage certainty ki guarantee nahi hai—ye sirf available data ke basis par signal strength batata hai.",points:["BUY: controlled entry ka setup mil raha hai","SELL: downside signal ya exit opportunity","NO TRADE: setup weak hai, capital wait karega"],action:{label:"Live AI decision dekho",href:"/trade/ai/decision?coin=BTC"}},
 {id:"risk",icon:"◇",title:"Risk kaise kaam karta hai",desc:"1% risk ko simple samjho",question:"₹10,000 capital par 1% risk kya hota hai?",answer:"1% risk ka matlab poora ₹10,000 lose karna nahi. Risk engine har trade ke stop-loss tak maximum planned loss ko lagbhag ₹100 ke andar rakhne ki koshish karta hai. Actual market slippage se result different ho sakta hai.",points:["Trading capital: ₹10,000 virtual","Maximum planned risk: ₹100 per trade","Daily 3% limit: ₹300 ke baad AI pause"],action:{label:"Risk settings kholo",href:"/trade/settings"}},
 {id:"paper",icon:"↗",title:"Paper trade kaise karein",desc:"Real money ke bina practice",question:"Mera pehla paper trade kaise hoga?",answer:"Market Scanner mein opportunity choose karo, AI reason padho, phir order review mein amount, Stop Loss aur Take Profit verify karo. Confirmation ke baad simulated order execute hoga—koi real money use nahi hota.",points:["Market choose karo","AI confidence aur reason padho","Amount + SL + TP verify karke confirm karo"],action:{label:"Paper trade try karo",href:"/trade/markets"}},
 {id:"auto",icon:"◉",title:"AI Auto Mode",desc:"AI ko controlled permission",question:"AI Auto Mode safe kaise rehta hai?",answer:"Auto Mode direct ON nahi hota. Pehle aap capital, per-trade risk, daily loss, markets aur minimum confidence set karte ho. Deterministic risk engine har signal ke beech mandatory gate hai; AI apni limits khud change nahi kar sakta.",points:["Stop Loss aur Take Profit mandatory","Daily loss limit ke baad automatic pause","Abnormal volatility mein new trade block"],action:{label:"Auto Mode setup dekho",href:"/trade/auto"}},
 {id:"profit",icon:"⌁",title:"Profit & loss reality",desc:"Guarantee nahi, measurement",question:"Kya AI guaranteed profit dega?",answer:"Nahi. Crypto market mein guaranteed profit ya fixed win rate honestly promise nahi ki ja sakti. ChatOnYou ka goal risk ko control karna, decisions explain karna aur paper results measure karna hai—pehle test, phir hi real integration consider hogi.",points:["Past paper result future guarantee nahi","NO TRADE bhi useful decision hai","Drawdown aur losses openly track honge"],action:{label:"Performance dekho",href:"/trade/analytics"}},
];
const englishTopics:Topic[]=[
 {id:"signal",icon:"✦",title:"Understand AI signals",desc:"BUY, SELL and NO TRADE",question:"What does an AI signal mean?",answer:"AI checks trend, momentum, volume, order-book pressure and volatility before returning BUY, SELL or NO TRADE. Confidence is not a guarantee; it only describes signal strength from the available data.",points:["BUY: a controlled entry setup is present","SELL: downside pressure or an exit signal","NO TRADE: the setup is weak, so capital waits"],action:{label:"View a live AI decision",href:"/trade/ai/decision?coin=BTC"}},
 {id:"risk",icon:"◇",title:"How risk works",desc:"Understand the 1% rule",question:"What does 1% risk mean on ₹10,000?",answer:"It does not mean losing the full ₹10,000. The risk engine sizes the planned loss between entry and stop-loss to roughly ₹100. Actual results can still differ because markets move.",points:["Trading capital: ₹10,000 virtual","Maximum planned risk: ₹100 per trade","Daily 3% limit: AI pauses after ₹300"],action:{label:"Open risk settings",href:"/trade/settings"}},
 {id:"paper",icon:"↗",title:"Place a paper trade",desc:"Practise without real money",question:"How do I place my first paper trade?",answer:"Choose an opportunity in Market Scanner, read the AI reason, then verify amount, Stop Loss and Take Profit in order review. After confirmation, a simulated order is saved without using real money.",points:["Choose a market","Read confidence and reasoning","Verify amount, SL and TP before confirming"],action:{label:"Try a paper trade",href:"/trade/markets"}},
 {id:"auto",icon:"◉",title:"AI Auto Mode",desc:"Controlled AI permission",question:"How does AI Auto stay controlled?",answer:"Auto Mode cannot start directly. You first approve capital, risk per trade, daily loss, markets and minimum confidence. The deterministic risk engine remains a mandatory gate and AI cannot change its own limits.",points:["Stop Loss and Take Profit stay mandatory","AI pauses after the daily loss limit","Abnormal volatility blocks new entries"],action:{label:"Review Auto Mode setup",href:"/trade/auto"}},
 {id:"profit",icon:"⌁",title:"Profit and loss reality",desc:"Measurement, not guarantees",question:"Does AI guarantee profit?",answer:"No. Honest crypto trading cannot promise fixed profit or a guaranteed win rate. ChatOnYou controls risk, explains decisions and measures paper results before any real integration is considered.",points:["Past results do not guarantee future returns","NO TRADE can be a valuable decision","Drawdown and losses remain visible"],action:{label:"View performance",href:"/trade/analytics"}},
];

export default function Guide(){
 const [selectedId,setSelectedId]=useState("signal"),[language,setLanguage]=useState("Hinglish"),[input,setInput]=useState(""),[asked,setAsked]=useState<string[]>([]),[sent,setSent]=useState(""),[feedback,setFeedback]=useState("");
 const activeTopics=language==="English"?englishTopics:topics,selected=activeTopics.find(topic=>topic.id===selectedId)||activeTopics[0];
 const ask=(topic:Topic)=>{setSelectedId(topic.id);setSent("");setFeedback("");if(!asked.includes(topic.id))setAsked(v=>[...v,topic.id])};
 const send=()=>{if(!input.trim())return;setSent(input);setInput("")};
 return <main className="guide-shell">
  <header className="guide-top"><a className="terminal-logo" href="/"><img src="/chatonyou-logo.png" alt="ChatOnYou"/><b>TRADE</b></a><div><i>✦</i><span><b>AI Guide</b><small>Beginner help · Paper mode</small></span></div><div><button onClick={()=>setLanguage(language==="Hinglish"?"English":"Hinglish")}>文 {language}</button><a href="/trade">×</a></div></header>
  <section className="guide-layout">
   <aside className="guide-topics"><header><span>LEARN CHATONYOU</span><h2>Start here</h2><p>Simple answers. No trading jargon.</p></header><nav>{activeTopics.map(t=><button className={selected.id===t.id?"active":""} onClick={()=>ask(t)} key={t.id}><i>{t.icon}</i><span><b>{t.title}</b><small>{t.desc}</small></span><em>{asked.includes(t.id)?"✓":"›"}</em></button>)}</nav><div className="guide-safety"><i>◇</i><span><b>Honest by design</b><small>No guaranteed profit claims. Risk is always visible.</small></span></div></aside>
   <section className="guide-chat">
    <header><div><span className="guide-avatar">✦<i/></span><span><b>ChatOnYou Guide</b><small>Scripted demo assistant</small></span></div><em>HINDI-FRIENDLY</em></header>
    <div className="guide-messages">
     <div className="guide-welcome"><span className="guide-avatar small">✦</span><div><p>{language==="English"?"Hello 👋 I’ll explain ChatOnYou Trade in simple language.":"Namaste 👋 Main aapko ChatOnYou Trade simple language mein samjhaunga."}</p><small>AI GUIDE · NOW</small></div></div>
     <div className="guide-user-message"><p>{selected.question}</p><small>YOU · NOW</small></div>
     <div className="guide-answer"><span className="guide-avatar small">✦</span><div><p>{selected.answer}</p><section>{selected.points.map((point,index)=><span key={point}><i>{index+1}</i>{point}</span>)}</section>{selected.action&&<a href={selected.action.href}>{selected.action.label} <b>→</b></a>}<footer><span>{feedback||"Helpful?"}</span><button aria-label="Mark answer helpful" aria-pressed={feedback==="Thanks for the feedback"} onClick={()=>setFeedback("Thanks for the feedback")}>👍</button><button aria-label="Mark answer not helpful" aria-pressed={feedback==="We’ll improve this answer"} onClick={()=>setFeedback("We’ll improve this answer")}>👎</button></footer></div></div>
     {sent&&<><div className="guide-user-message"><p>{sent}</p><small>YOU · NOW</small></div><div className="guide-answer compact"><span className="guide-avatar small">✦</span><div><p>{language==="English"?"This demo guide currently uses predefined answers. Connected AI support can later understand exact questions and reply in the selected language.":"Ye demo guide abhi predefined answers use karta hai. Connected AI support baad mein exact question samajhkar selected language mein reply kar sakta hai."}</p><a href="/trade/guide">{language==="English"?"Continue with recommended topics":"Recommended topics se continue karein"} <b>↑</b></a></div></div></>}
    </div>
    <div className="guide-composer"><div className="guide-suggestions">{activeTopics.filter(t=>t.id!==selected.id).slice(0,3).map(t=><button onClick={()=>ask(t)} key={t.id}>{t.title}</button>)}</div><div><button disabled title="Attachments are unavailable in the educational demo" aria-label="Attachments unavailable">+</button><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder={language==="English"?"Ask a question in English…":"Apna question Hinglish mein poochho…"}/><button aria-label="Send question" onClick={send} disabled={!input.trim()}>↑</button></div><small>Demo guide · Predefined educational answers · Not financial advice</small></div>
   </section>
   <aside className="guide-progress">
    <header><span>YOUR PROGRESS</span><strong>{asked.length}<small>/ {topics.length}</small></strong><div><i style={{width:(asked.length/topics.length*100)+"%"}}/></div><p>{asked.length===topics.length?"Basics complete!":"Learn the basics before Auto Mode."}</p></header>
    <section><h3>Beginner checklist</h3>{activeTopics.map(t=><button className={asked.includes(t.id)?"done":""} onClick={()=>ask(t)} key={t.id}><i>{asked.includes(t.id)?"✓":""}</i><span><b>{t.title}</b><small>{asked.includes(t.id)?"Completed":"2 min read"}</small></span></button>)}</section>
    <article><i>✦</i><span><b>Try with ₹10,000 virtual</b><small>Practice every flow safely before connecting anything real.</small></span><a href="/trade">Open terminal →</a></article>
    <footer><a href="/trade/localization">Language preferences</a><a href="/trade/settings">Risk settings</a></footer>
   </aside>
  </section>
 </main>
}
