"use client";

import { useState } from "react";

const steps = ["Consent", "Personal details", "Address", "Verification", "Review"];

type FormState = {
  consent: boolean; fullName: string; dob: string; nationality: string; pan: string; email: string; mobile: string; address: string; city: string; state: string; pincode: string; idType: string; idNumber: string; idFile: string; addressFile: string; selfieReady: boolean; bankReady: boolean; declaration: boolean;
};

const initialForm: FormState = { consent: false, fullName: "", dob: "", nationality: "Indian", pan: "", email: "", mobile: "", address: "", city: "", state: "", pincode: "", idType: "Aadhaar", idNumber: "", idFile: "", addressFile: "", selfieReady: false, bankReady: false, declaration: false };
const requiredDocuments = ["PAN", "Government identity", "Address proof", "Liveness selfie", "Bank account proof"];

export default function KycPage() {
  const [step, setStep] = useState(0);
  const [form, setForm] = useState<FormState>(initialForm);
  const [error, setError] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [reference, setReference] = useState("");
  const update = <K extends keyof FormState,>(key: K, value: FormState[K]) => setForm((current) => ({ ...current, [key]: value }));
  const validate = () => {
    if (step === 0 && !form.consent) return "Please accept the KYC consent to continue.";
    if (step === 1 && (!form.fullName || !form.dob || !/^[A-Z]{5}[0-9]{4}[A-Z]$/.test(form.pan.toUpperCase()))) return "Enter full name, date of birth and a valid PAN format.";
    if (step === 2 && (!form.email.includes("@") || form.mobile.replace(/\D/g, "").length < 10 || !form.address || !form.city || !form.state || form.pincode.length !== 6)) return "Complete the contact and residential-address details.";
    if (step === 3 && (!form.idNumber || !form.idFile || !form.addressFile || !form.selfieReady || !form.bankReady)) return "Complete the document, selfie and bank verification checks.";
    return "";
  };
  const next = () => { const issue = validate(); if (issue) { setError(issue); return; } setError(""); setStep((value) => Math.min(4, value + 1)); };
  const back = () => { setError(""); setStep((value) => Math.max(0, value - 1)); };
  const submit = async () => {
    if (!form.declaration) { setError("Accept the final declaration before submission."); return; }
    setSubmitting(true); setError("");
    try {
      const response = await fetch("/api/kyc", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, evidence: { identityDocumentSelected: Boolean(form.idFile), addressDocumentSelected: Boolean(form.addressFile), selfieCheckReady: form.selfieReady, bankCheckReady: form.bankReady } }) });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error || "KYC submission could not be saved.");
      setReference(data.application.reference); setSubmitted(true);
    } catch (reason) { setError(reason instanceof Error ? reason.message : "KYC submission could not be saved."); }
    finally { setSubmitting(false); }
  };
  const completedChecks = [form.pan, form.idFile, form.addressFile, form.selfieReady ? "yes" : "", form.bankReady ? "yes" : ""].filter(Boolean).length;
  const progress = Math.min(100, Math.round(((step + completedChecks / 5) / 4.8) * 100));

  if (submitted) return <main className="kyc-shell"><header className="kyc-top"><a href="/" className="kyc-logo"><img src="/chatonyou-logo.png" alt="ChatOnYou"/><b>TRADE</b></a><span>Client KYC</span><a href="/">×</a></header><section className="kyc-result"><div className="kyc-result-icon">✓</div><span>KYC SUBMITTED</span><h1>KYC received.<br/><em>Compliance review is pending.</em></h1><p>Your reference is <b>{reference}</b>. NEOCRAFT LLP’s authorised reviewer must complete identity, sanctions and risk checks before approval.</p><div><article><small>KYC STATUS</small><b>Pending review</b></article><article><small>DATA SAVED</small><b>Minimised metadata</b></article><article><small>ACCOUNT ACCESS</small><b>Locked until approved</b></article></div><nav><a href="/kyc/status">View KYC status</a><button onClick={()=>{setSubmitted(false);setStep(0);setForm(initialForm)}}>Update application</button></nav><small>Selected document files remain on this device until an approved verification provider is connected.</small></section></main>;

  return <main className="kyc-shell">
    <header className="kyc-top"><a href="/" className="kyc-logo"><img src="/chatonyou-logo.png" alt="ChatOnYou"/><b>TRADE</b></a><span>Client KYC</span><a href="/compliance">×</a></header>
    <div className="kyc-progress" style={{gridTemplateColumns:"repeat(5,1fr)"}} aria-label={`Step ${step + 1} of ${steps.length}`}>{steps.map((item,index)=><button key={item} type="button" onClick={()=>index<step&&setStep(index)} className={index===step?"active":index<step?"done":""}><i>{index<step?"✓":index+1}</i><span>{item}</span>{index<steps.length-1?<b/>:null}</button>)}</div>
    <div className="kyc-layout"><section className="kyc-card">
      {step===0?<div className="kyc-step"><header><span>STEP 1 OF 5 · CONSENT</span><h1>Complete your KYC.</h1><p>We only retain the minimum review metadata needed to manage your application.</p></header><div className="kyc-notice"><i>◇</i><div><b>Privacy boundary</b><p>Full PAN, Aadhaar/document numbers and selected file contents are not stored by this workflow. Formal verification must run through an approved provider.</p></div></div><label className="kyc-check"><input type="checkbox" checked={form.consent} onChange={event=>update("consent",event.target.checked)}/><span><b>I consent to identity verification</b><small>I confirm that my information is accurate and may be verified by NEOCRAFT LLP through authorised providers.</small></span></label><div className="kyc-why"><b>What the reviewer must verify</b><p>PAN, government identity, address, liveness, bank-account name and sanctions/PEP screening.</p></div></div>:null}
      {step===1?<div className="kyc-step"><header><span>STEP 2 OF 5 · PERSONAL DETAILS</span><h1>Tell us who you are.</h1><p>These details must match the documents used for verification.</p></header><div className="kyc-fields two"><label>Full legal name<input value={form.fullName} onChange={event=>update("fullName",event.target.value)} placeholder="As shown on PAN" autoComplete="name"/></label><label>Date of birth<input type="date" value={form.dob} onChange={event=>update("dob",event.target.value)} autoComplete="bday"/></label><label>Nationality<select value={form.nationality} onChange={event=>update("nationality",event.target.value)}><option>Indian</option><option>Other</option></select></label><label>PAN<input value={form.pan} onChange={event=>update("pan",event.target.value.toUpperCase())} placeholder="ABCDE1234F" maxLength={10}/><small>Demo format check only</small></label></div></div>:null}
      {step===2?<div className="kyc-step"><header><span>STEP 3 OF 5 · CONTACT &amp; ADDRESS</span><h1>Where can we reach you?</h1><p>Add your verified contact details and current residential address.</p></header><div className="kyc-fields two"><label>Email address<input type="email" value={form.email} onChange={event=>update("email",event.target.value)} placeholder="name@example.com" autoComplete="email"/></label><label>Mobile number<input value={form.mobile} onChange={event=>update("mobile",event.target.value)} placeholder="+91 98765 43210" autoComplete="tel"/></label><label className="wide">Residential address<textarea value={form.address} onChange={event=>update("address",event.target.value)} placeholder="House, street and locality" autoComplete="street-address"/></label><label>City<input value={form.city} onChange={event=>update("city",event.target.value)} autoComplete="address-level2"/></label><label>State<input value={form.state} onChange={event=>update("state",event.target.value)} autoComplete="address-level1"/></label><label>PIN code<input inputMode="numeric" value={form.pincode} onChange={event=>update("pincode",event.target.value.replace(/\D/g,"").slice(0,6))} placeholder="302006" autoComplete="postal-code"/></label></div></div>:null}
      {step===3?<div className="kyc-step"><header><span>STEP 4 OF 5 · VERIFICATION</span><h1>Prepare verification evidence.</h1><p>Select the evidence required for review. File contents stay on this device until the approved provider hand-off is connected.</p></header><div className="kyc-fields two"><label>Identity document<select value={form.idType} onChange={event=>update("idType",event.target.value)}><option>Aadhaar</option><option>Passport</option><option>Driving licence</option><option>Voter ID</option></select></label><label>Document reference<input value={form.idNumber} onChange={event=>update("idNumber",event.target.value)} placeholder="Do not enter full Aadhaar number"/></label></div><div className="kyc-upload-grid"><label><input type="file" accept="image/*,.pdf" onChange={event=>update("idFile",event.target.files?.[0]?.name||"")}/><i>▣</i><b>{form.idFile||"Identity document"}</b><small>{form.idFile?"Selected locally":"PDF, JPG or PNG"}</small></label><label><input type="file" accept="image/*,.pdf" onChange={event=>update("addressFile",event.target.files?.[0]?.name||"")}/><i>⌂</i><b>{form.addressFile||"Address proof"}</b><small>{form.addressFile?"Selected locally":"Recent accepted proof"}</small></label></div><div className="kyc-verification-actions"><button type="button" className={form.selfieReady?"done":""} onClick={()=>update("selfieReady",true)}><i>{form.selfieReady?"✓":"◎"}</i><span><b>Liveness readiness</b><small>{form.selfieReady?"Ready for provider check":"Confirm selfie can be completed"}</small></span></button><button type="button" className={form.bankReady?"done":""} onClick={()=>update("bankReady",true)}><i>{form.bankReady?"✓":"₹"}</i><span><b>Bank-name readiness</b><small>{form.bankReady?"Ready for provider check":"Confirm bank check can be completed"}</small></span></button></div></div>:null}
      {step===4?<div className="kyc-step"><header><span>STEP 5 OF 5 · REVIEW</span><h1>Review your KYC.</h1><p>Confirm the details before submitting them for identity verification.</p></header><div className="kyc-review"><article><span><small>CLIENT</small><b>{form.fullName||"Not provided"}</b></span><em>PAN format checked</em></article><article><span><small>CONTACT</small><b>{form.email}</b></span><em>{form.mobile}</em></article><article><span><small>ADDRESS</small><b>{form.city}, {form.state}</b></span><em>PIN {form.pincode}</em></article><article><span><small>IDENTITY PROOF</small><b>{form.idType}</b></span><em>{form.idFile}</em></article></div><div className="kyc-final-gates"><span><i>✓</i>PAN details ready</span><span><i>✓</i>Identity proof ready</span><span><i>✓</i>Address proof ready</span><span><i>✓</i>Liveness demo complete</span><span><i>✓</i>Bank demo complete</span><span className="pending"><i>…</i>Provider verification pending</span></div><label className="kyc-check final"><input type="checkbox" checked={form.declaration} onChange={event=>update("declaration",event.target.checked)}/><span><b>I confirm these KYC details are correct</b><small>I authorise verification of the submitted information in a production process.</small></span></label></div>:null}
      {error?<p className="kyc-error" role="alert">{error}</p>:null}<footer className="kyc-actions"><button type="button" onClick={back} disabled={step===0||submitting}>← Back</button><span>Step {step+1} of {steps.length}</span>{step<4?<button type="button" className="primary" onClick={next}>Continue <i>→</i></button>:<button type="button" className="primary" onClick={submit} disabled={submitting}>{submitting?"Saving securely…":"Submit for review"} <i>↗</i></button>}</footer>
    </section><aside className="kyc-aside"><div className="kyc-aside-status"><span>KYC COMPLETION</span><strong>{progress}%</strong><div><i style={{width:`${Math.max(5,progress)}%`}}/></div><p>Account access stays locked until identity verification is complete.</p></div><section><h2>Required documents</h2>{requiredDocuments.map((item,index)=><div key={item} className={index<completedChecks?"done":""}><i>{index<completedChecks?"✓":index+1}</i><span><b>{item}</b><small>{index<completedChecks?"Ready for demo review":"Required for KYC"}</small></span></div>)}</section><div className="kyc-security"><i>◇</i><span><b>Secure KYC</b><small>Production documents require encryption, restricted access and controlled retention.</small></span></div><a href="/privacy">Read privacy policy →</a></aside></div>
  </main>;
}
