"use client";
import { useEffect,useState } from "react";

type ImportedResult={return:string;drawdown:string;trades:number};

export default function BotImport(){
 const [step,setStep]=useState(1),[confidence,setConfidence]=useState(82),[risk,setRisk]=useState(1),[name,setName]=useState("Trend Rider · BTC"),[strategy,setStrategy]=useState("trend"),[strategyName,setStrategyName]=useState("Trend Rider"),[market,setMarket]=useState("BTC/USDT"),[timeframe,setTimeframe]=useState("1h"),[result,setResult]=useState<ImportedResult>({return:"+11.8%",drawdown:"-3.2%",trades:48}),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState("");
 useEffect(()=>{try{const raw=sessionStorage.getItem("chatonyou:backtest-import");if(!raw)return;const saved=JSON.parse(raw);if(!["trend","breakout","defensive"].includes(saved.strategy)||typeof saved.strategyName!=="string"||typeof saved.market!=="string"||typeof saved.timeframe!=="string")return;setStrategy(saved.strategy);setStrategyName(saved.strategyName);setMarket(saved.market);setTimeframe(saved.timeframe);setRisk(Number(saved.risk)||1);setResult({return:String(saved.result?.return||"—"),drawdown:String(saved.result?.drawdown||"—"),trades:Number(saved.result?.trades)||0});setName(`${saved.strategyName} · ${saved.market.split("/")[0]}`)}catch{}},[]);
 const createBot=async()=>{const bot={name,strategy,coins:[market.split("/")[0]],market,timeframe,confidence,risk,dailyLoss:3,active:true,archived:false,createdAt:Date.now()};setSaving(true);setSaveError("");try{const response=await fetch("/api/bots",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(bot)});const data=await response.json();if(!response.ok)throw new Error(data.error||"Paper bot could not be saved");sessionStorage.setItem("chatonyou:paper-bot",JSON.stringify(data.bot||bot));setStep(3)}catch(reason){setSaveError(reason instanceof Error?reason.message:"Paper bot could not be saved")}finally{setSaving(false)}};
 return <main className="finish-flow-shell bot-import-shell"><header className="finish-flow-top"><a className="terminal-logo" href="/"><img src="/chatonyou-logo.png" alt="ChatOnYou"/><b>TRADE</b></a><div><i>◫</i><span><b>Backtest Import</b><small>Paper strategy handoff</small></span></div><a href="/trade/backtest">×</a></header>
  {step<3?<section className="finish-flow-main"><div className="finish-flow-copy"><span>BACKTEST → PAPER BOT</span><h1>Result captured.<br/><em>Now recheck the rules.</em></h1><p>Historical performance is only a starting point. Live paper-risk limits apply independently before the bot can activate.</p><div className="import-result"><span><small>BACKTEST RETURN</small><b>{result.return}</b></span><span><small>MAX DRAWDOWN</small><b>{result.drawdown}</b></span><span><small>TRADES</small><b>{result.trades}</b></span><em>Illustrative</em></div></div>
   <section className="finish-card import-card"><header><div><span>{step===1?"IMPORT REVIEW":"ACTIVATION REVIEW"}</span><h2>{step===1?"Map strategy settings":"Confirm controlled bot"}</h2></div><i>PAPER BOT</i></header>{step===1?<div className="import-form"><label>Bot name<input value={name} onChange={e=>setName(e.target.value)}/></label><div><label>Market<select value={market} onChange={e=>setMarket(e.target.value)}><option>BTC/USDT</option><option>ETH/USDT</option><option>SOL/USDT</option></select></label><label>Timeframe<select value={timeframe} onChange={e=>setTimeframe(e.target.value)}><option>15m</option><option>1h</option><option>4h</option></select></label></div><label>Minimum AI confidence <b>{confidence}%</b><input type="range" min="70" max="95" value={confidence} onChange={e=>setConfidence(Number(e.target.value))}/></label><label>Maximum risk per trade <b>{risk}%</b><input type="range" min=".5" max="2" step=".5" value={risk} onChange={e=>setRisk(Number(e.target.value))}/></label></div>:<div className="import-review"><span><small>STRATEGY</small><b>{strategyName}</b></span><span><small>MARKET</small><b>{market} · {timeframe}</b></span><span><small>CONFIDENCE</small><b>{confidence}% minimum</b></span><span><small>RISK</small><b>{risk}% / trade</b></span><span><small>MANDATORY</small><b>Stop-loss + take-profit</b></span><span><small>MODE</small><b>Paper only</b></span><div className="finish-note"><i>◇</i><span><b>Backtest return is not a promise</b><small>Future results can differ; daily-loss and volatility rules remain active.</small></span></div></div>}
    {saveError&&<p role="alert" className="ai-data-note">{saveError}</p>}<footer><button onClick={()=>step===1?window.location.href="/trade/backtest":setStep(1)}>Back</button><button disabled={!name||saving} onClick={()=>step===1?setStep(2):createBot()}>{step===1?"Review bot":saving?"Saving…":"Create paper bot"}<b>→</b></button></footer></section></section>:
   <section className="finish-success"><div><i>✦</i><span/><b/></div><span>PAPER BOT CREATED</span><h1>Imported safely.<br/><em>Watching, not trading yet.</em></h1><p>{name} will wait for a signal above {confidence}% and every deterministic risk check.</p><article><span>Current decision<b>NO TRADE</b></span><span>Market<b>{market}</b></span><span>Risk / trade<b>{risk}%</b></span></article><div><a href="/trade/bots">Manage paper bot</a><a href="/trade/ai">View AI activity</a></div><small>Backtest data is illustrative · No guaranteed return</small></section>}
 </main>
}
