"use client";
import { useState } from "react";

const steps=["AI Mode","Risk Rules","Markets","Ready"];
const modes=[
 {id:"copilot",icon:"✦",title:"AI Copilot",tag:"Recommended",text:"AI analyses continuously. You confirm every paper trade."},
 {id:"assisted",icon:"↗",title:"AI Assisted",tag:"One-click approve",text:"AI finds opportunities and prepares the full order for you."},
 {id:"auto",icon:"◉",title:"AI Auto",tag:"Advanced",text:"AI enters and exits automatically within your strict limits."},
];
const coins=[{id:"BTC",name:"Bitcoin",color:"#f5a623"},{id:"ETH",name:"Ethereum",color:"#8093ff"},{id:"SOL",name:"Solana",color:"#8dffc2"},{id:"BNB",name:"BNB",color:"#f3d55b"}];

export default function Setup(){
 const [step,setStep]=useState(0),[mode,setMode]=useState("copilot"),[capital,setCapital]=useState(10000),[risk,setRisk]=useState(1),[loss,setLoss]=useState(3),[positions,setPositions]=useState(2),[selected,setSelected]=useState(["BTC","ETH","SOL"]),[safety,setSafety]=useState({stop:true,target:true,volatility:true}),[launching,setLaunching]=useState(false),[error,setError]=useState("");
 const next=()=>setStep(value=>Math.min(3,value+1)),back=()=>setStep(value=>Math.max(0,value-1));
 const toggleCoin=(coin:string)=>setSelected(current=>current.includes(coin)?current.filter(item=>item!==coin):[...current,coin]);
 const launch=async()=>{setLaunching(true);setError("");try{const response=await fetch("/api/account",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({mode,settings:{capital,maxRisk:risk,dailyLoss:loss,maxPositions:positions,minConfidence:80,stopLoss:safety.stop,takeProfit:safety.target,volatility:safety.volatility}})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Setup could not be saved");localStorage.setItem("chatonyou-trade-setup",JSON.stringify({mode,capital,risk,loss,positions,selected,safety}));window.location.href="/trade/first-trade"}catch(reason){setError(reason instanceof Error?reason.message:"Setup could not be saved");setLaunching(false)}};
 return <main className="setup-shell"><div className="setup-orb"/><div className="setup-grid-bg"/>
  <header className="setup-header"><a href="/" className="setup-logo"><img src="/chatonyou-logo.png" alt="ChatOnYou"/><b>TRADE</b></a><span>Paper account setup</span><a href="/trade">Skip setup</a></header>
  <div className="setup-progress">{steps.map((name,index)=><div className={index===step?"active":index<step?"done":""} key={name}><i>{index<step?"✓":index+1}</i><span>{name}</span>{index<steps.length-1&&<b/>}</div>)}</div>
  <section className="setup-card">
   {step===0&&<div className="setup-step mode-step"><div className="setup-title"><span>STEP 1 OF 4</span><h1>How should AI help you?</h1><p>Start with full control. You can change this anytime.</p></div><div className="setup-modes">{modes.map(item=><button key={item.id} onClick={()=>setMode(item.id)} className={mode===item.id?"selected":""}><i>{item.icon}</i><div><span>{item.tag}</span><h2>{item.title}</h2><p>{item.text}</p></div><b>{mode===item.id?"✓":""}</b></button>)}</div><div className="setup-note"><i>◇</i><p><b>Paper mode stays active</b><span>No exchange connection and no real money will be used.</span></p></div></div>}
   {step===1&&<div className="setup-step risk-step"><div className="setup-title"><span>STEP 2 OF 4</span><h1>Set your safety limits.</h1><p>The risk engine checks these rules before every decision.</p></div><div className="capital-input"><span>Virtual trading capital</span><label>₹<input value={capital} onChange={event=>setCapital(Number(event.target.value))}/></label><small>Recommended ₹10,000</small></div><div className="risk-sliders"><label><span>Maximum risk per trade <b>{risk}%</b></span><input type="range" min="0.5" max="3" step="0.5" value={risk} onChange={e=>setRisk(Number(e.target.value))}/><small>₹{Math.round(capital*risk/100)} maximum planned risk</small></label><label><span>Daily maximum loss <b>{loss}%</b></span><input type="range" min="1" max="8" value={loss} onChange={e=>setLoss(Number(e.target.value))}/><small>AI pauses at ₹{Math.round(capital*loss/100)} daily loss</small></label><label><span>Maximum open positions <b>{positions}</b></span><input type="range" min="1" max="5" value={positions} onChange={e=>setPositions(Number(e.target.value))}/><small>Limits simultaneous exposure</small></label></div><div className="safety-toggles">{[["stop","Always use stop loss"],["target","Always use take profit"],["volatility","Pause during abnormal volatility"]].map(([key,label])=><button key={key} onClick={()=>setSafety(current=>({...current,[key]:!current[key as keyof typeof current]}))}><span>{label}</span><i className={safety[key as keyof typeof safety]?"on":""}/></button>)}</div></div>}
   {step===2&&<div className="setup-step markets-step"><div className="setup-title"><span>STEP 3 OF 4</span><h1>Choose markets to watch.</h1><p>AI will analyse these coins continuously. Select at least one.</p></div><div className="coin-select">{coins.map(coin=><button key={coin.id} onClick={()=>toggleCoin(coin.id)} className={selected.includes(coin.id)?"selected":""}><i style={{background:coin.color}}>{coin.id[0]}</i><span><b>{coin.id}/USDT</b><small>{coin.name}</small></span><em>{selected.includes(coin.id)?"✓":"+"}</em></button>)}</div><div className="watch-preview"><span><i/> AI WATCHLIST</span><strong>{selected.length} markets selected</strong><p>{selected.length?selected.join(" · "):"Select at least one market to continue"}</p></div></div>}
   {step===3&&<div className="setup-step ready-step"><div className="ready-check">✓</div><div className="setup-title"><span>SETUP COMPLETE</span><h1>Your AI workspace is ready.</h1><p>Review the safety settings below, then enter paper trading.</p></div><div className="setup-summary"><div><span>AI mode</span><b>{modes.find(item=>item.id===mode)?.title}</b></div><div><span>Virtual capital</span><b>₹{capital.toLocaleString("en-IN")}</b></div><div><span>Risk per trade</span><b>{risk}%</b></div><div><span>Daily loss limit</span><b>{loss}%</b></div><div><span>Open positions</span><b>Maximum {positions}</b></div><div><span>AI markets</span><b>{selected.join(", ")}</b></div></div><div className="ready-status"><i/><span><b>Risk engine active</b><small>Every paper order will be validated before execution.</small></span></div></div>}
   {error&&<p className="order-api-error">{error}</p>}<footer className="setup-actions"><button onClick={back} disabled={step===0||launching}>← Back</button><span>Settings can be changed later</span>{step<3?<button className="setup-next" onClick={next} disabled={step===2&&selected.length===0}>Continue <i>→</i></button>:<button className="setup-next launch" onClick={launch} disabled={launching}>{launching?"Saving setup…":"Launch paper trading"} <i>↗</i></button>}</footer>
  </section><p className="setup-disclaimer">Paper trading only · Illustrative market data · No guaranteed returns</p>
 </main>
}
