"use client";

import { useCallback, useEffect, useState } from "react";

type Client={userEmail:string;fullName:string;reference:string;status:string};
type Check={id:string;label:string;passed:boolean;detail:string};
type Drill={id:string;userEmail:string;status:string;automaticChecks:Check[];manualChecks:string[];note:string;conductedBy:string;conductedAt:number};
const manual=[{id:"incident_contacts",title:"Incident contacts verified",text:"Principal Officer, security lead and legal escalation contacts were checked."},{id:"notification_delivery",title:"Client notifications tested",text:"Trade, loss and emergency notifications reached the intended test account."},{id:"reconciliation",title:"Order reconciliation completed",text:"Testnet exchange status matched internal history and portfolio records."},{id:"recovery_review",title:"Recovery procedure reviewed",text:"Safe resume, credential rotation and evidence preservation steps were rehearsed."}];

export default function ReadinessDrillClient({reviewerEmail}:{reviewerEmail:string}){
 const [clients,setClients]=useState<Client[]>([]),[drills,setDrills]=useState<Drill[]>([]),[selected,setSelected]=useState(""),[checks,setChecks]=useState<string[]>([]),[note,setNote]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=useCallback(async()=>{setError("");try{const response=await fetch("/api/admin/readiness-drill",{cache:"no-store"}),body=await response.json();if(!response.ok)throw new Error(body.error||"Drill workspace unavailable");setClients(body.applications);setDrills(body.drills);setSelected(current=>current||body.applications[0]?.userEmail||"")}catch(reason){setError(reason instanceof Error?reason.message:"Drill workspace unavailable")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const toggle=(id:string)=>setChecks(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);
 const record=async()=>{setSaving(true);setError("");setMessage("");try{const response=await fetch("/api/admin/readiness-drill",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({userEmail:selected,manualChecks:checks,note})}),body=await response.json();if(!response.ok)throw new Error(body.error||"Drill could not be recorded");setMessage(body.status==="passed"?"Controlled pilot passed and evidence was recorded.":"Drill recorded with automatic blockers. Resolve them and run again.");setChecks([]);setNote("");await load()}catch(reason){setError(reason instanceof Error?reason.message:"Drill could not be recorded")}finally{setSaving(false)}};
 const latest=drills.find(item=>item.userEmail===selected),client=clients.find(item=>item.userEmail===selected);
 return <main className="admin-kyc-shell drill-shell"><header className="admin-kyc-top"><a href="/"><img src="/chatonyou-logo.png" alt="ChatOnYou"/><b>TRADE</b></a><span>NEOCRAFT LLP · CONTROLLED PILOT</span><div><small>Authorised reviewer</small><b>{reviewerEmail}</b><a href="/admin/launch-review">Launch review</a><a href="/logout">Sign out</a></div></header>
  <section className="drill-hero"><div><span>END-TO-END REHEARSAL</span><h1>Prove the safety path.</h1><p>Run this only with paper trading and Binance Spot Testnet. The system verifies saved evidence when the drill is recorded.</p></div><article className={latest?.status||"pending"}><small>LATEST RESULT</small><b>{latest?latest.status.toUpperCase():"NOT RUN"}</b><em>{latest?new Date(latest.conductedAt).toLocaleString("en-IN"):"No saved rehearsal"}</em></article></section>
  <section className="drill-layout"><div className="drill-run"><header><span>01 · SELECT TEST CLIENT</span><select value={selected} onChange={event=>{setSelected(event.target.value);setChecks([]);setMessage("")}}>{clients.map(item=><option value={item.userEmail} key={item.userEmail}>{item.fullName} · {item.reference}</option>)}</select></header>{loading?<p className="evidence-empty">Loading controlled-pilot evidence…</p>:client?<><div className="drill-client"><i>{client.fullName.split(/\s+/).slice(0,2).map(item=>item[0]).join("")}</i><div><b>{client.fullName}</b><small>{client.userEmail} · KYC {client.status.replace("_"," ")}</small></div></div><section className="drill-manual"><header><span>02 · COMPLETE MANUAL REHEARSAL</span><b>{checks.length}/{manual.length}</b></header>{manual.map(item=><button className={checks.includes(item.id)?"done":""} onClick={()=>toggle(item.id)} key={item.id}><i>{checks.includes(item.id)?"✓":"○"}</i><span><b>{item.title}</b><small>{item.text}</small></span></button>)}</section><label className="drill-note">03 · DRILL OBSERVATIONS<textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="Record who participated, what was tested, any mismatch found and follow-up owner."/></label>{error?<p className="admin-error" role="alert">{error}</p>:null}{message?<p className="admin-message">✓ {message}</p>:null}<footer><small>Automatic evidence is re-checked on save. A failed drill never clears a launch gate.</small><button disabled={saving||checks.length!==manual.length||note.trim().length<30} onClick={()=>void record()}>{saving?"Verifying evidence…":"Record controlled pilot"} <b>→</b></button></footer></>:<p className="evidence-empty">Submit a KYC application before running a pilot.</p>}</div>
  <aside className="drill-history"><header><span>SAVED DRILL HISTORY</span><b>{drills.length} runs</b></header>{drills.length?drills.map(item=><article key={item.id}><i className={item.status}>{item.status==="passed"?"✓":"!"}</i><div><header><b>{item.userEmail}</b><em>{item.status}</em></header><p>{item.automaticChecks.filter(check=>check.passed).length}/{item.automaticChecks.length} automatic · {item.manualChecks.length}/{manual.length} manual</p><small>{item.conductedBy} · {new Date(item.conductedAt).toLocaleString("en-IN")}</small><blockquote>{item.note}</blockquote></div></article>):<p className="evidence-empty">No controlled pilot has been recorded.</p>}</aside></section>
  <footer className="admin-kyc-footer">Paper/Testnet rehearsal only · No real deposit, withdrawal, custody or exchange order is enabled.</footer>
 </main>
}
