"use client";

import { useEffect,useState } from "react";

type Language="EN"|"HI";

const exact:Record<string,string>={
 "Paper trading only":"केवल पेपर ट्रेडिंग","Back to home":"होम पर वापस","WELCOME BACK":"वापसी पर स्वागत है","Sign in to Trade.":"ट्रेड में साइन इन करें।","Continue to your AI paper-trading workspace.":"अपने AI पेपर-ट्रेडिंग वर्कस्पेस में जाएँ।","Continue securely with ChatGPT":"ChatGPT से सुरक्षित रूप से जारी रखें","SECURE PLATFORM SIGN-IN":"सुरक्षित प्लेटफ़ॉर्म साइन-इन","Email address":"ईमेल पता","Password":"पासवर्ड","Keep me signed in":"मुझे साइन इन रखें","Forgot password?":"पासवर्ड भूल गए?","Continue with ChatGPT":"ChatGPT के साथ जारी रखें","New to ChatOnYou Trade?":"ChatOnYou Trade पर नए हैं?","Create account":"अकाउंट बनाएँ","Why sign-in is required":"साइन-इन क्यों ज़रूरी है","It keeps your paper balance and settings tied to you.":"यह आपका पेपर बैलेंस और सेटिंग्स सुरक्षित रखता है।","Privacy":"गोपनीयता","Terms":"शर्तें","Risk disclosure":"जोखिम सूचना",
 "Paper account setup":"पेपर अकाउंट सेटअप","Skip setup":"सेटअप छोड़ें","AI Mode":"AI मोड","Risk Rules":"जोखिम नियम","Markets":"मार्केट","Ready":"तैयार","How should AI help you?":"AI आपकी मदद कैसे करे?","Start with full control. You can change this anytime.":"पूरे नियंत्रण के साथ शुरू करें। इसे कभी भी बदल सकते हैं।","Set your safety limits.":"अपनी सुरक्षा सीमाएँ तय करें।","Choose markets to watch.":"देखने के लिए मार्केट चुनें।","Your AI workspace is ready.":"आपका AI वर्कस्पेस तैयार है।","Settings can be changed later":"सेटिंग्स बाद में बदली जा सकती हैं","Launch paper trading":"पेपर ट्रेडिंग शुरू करें","Continue":"जारी रखें","Back":"वापस",
 "CONTROL CENTER":"कंट्रोल सेंटर","Settings & risk":"सेटिंग्स और जोखिम","Save changes":"बदलाव सेव करें","Reset defaults":"डिफ़ॉल्ट रीसेट करें","RISK MANAGEMENT":"जोखिम प्रबंधन","Protect the account first.":"पहले अकाउंट की सुरक्षा करें।","Capital limits":"पूँजी सीमाएँ","Loss protection":"नुकसान सुरक्षा","Mandatory protection":"अनिवार्य सुरक्षा","Trading capital":"ट्रेडिंग पूँजी","Maximum risk per trade":"हर ट्रेड का अधिकतम जोखिम","Daily maximum loss":"दैनिक अधिकतम नुकसान","Maximum open positions":"अधिकतम खुली पोज़िशन","Always use stop-loss":"हमेशा Stop Loss लगाएँ","Always use take-profit":"हमेशा Take Profit लगाएँ","Save & apply":"सेव करके लागू करें",
 "Open positions":"खुली पोज़िशन","Trade history":"ट्रेड इतिहास","AI Decisions":"AI निर्णय","AI activity":"AI गतिविधि","Account center":"अकाउंट केंद्र","Your profile":"आपकी प्रोफ़ाइल","Quick access":"त्वरित पहुँच","Language & region":"भाषा और क्षेत्र","Risk settings":"जोखिम सेटिंग्स","Demo balance":"डेमो बैलेंस","Available balance":"उपलब्ध बैलेंस","Paper balance":"पेपर बैलेंस","No real money":"कोई असली पैसा नहीं","No exchange order":"कोई एक्सचेंज ऑर्डर नहीं","No guaranteed returns":"रिटर्न की कोई गारंटी नहीं",
 "BUY":"खरीदें","SELL":"बेचें","NO TRADE":"अभी ट्रेड नहीं","OPEN":"खुला","CLOSED":"बंद","ACTIVE":"सक्रिय","READY":"तैयार","BLOCKED":"रुका हुआ","PROTECTED":"सुरक्षित","PASSED":"पास","PAUSED":"रुका हुआ","SCANNING":"स्कैन जारी","Close":"बंद करें","Cancel":"रद्द करें","Confirm":"पुष्टि करें","Manage":"मैनेज करें","Edit":"बदलें","View all":"सभी देखें","Try again":"फिर कोशिश करें","Loading…":"लोड हो रहा है…","Saving…":"सेव हो रहा है…","Search":"खोजें","Today":"आज","Status":"स्थिति","Decision":"निर्णय","Confidence":"विश्वास","Market":"मार्केट","Price":"कीमत","Amount":"राशि","Balance":"बैलेंस","Safety":"सुरक्षा","Settings":"सेटिंग्स","History":"इतिहास","Portfolio":"पोर्टफोलियो","Wallet":"वॉलेट","Profile":"प्रोफ़ाइल","Analytics":"विश्लेषण","Guide":"गाइड","Trade":"ट्रेड"
};

const phrases:Array<[string,string]>=[
 ["AI is watching the market","AI मार्केट देख रहा है"],["AI analyses continuously","AI लगातार विश्लेषण करता है"],["AI finds opportunities","AI अवसर खोजता है"],["AI enters and exits automatically","AI अपने-आप एंट्री और एग्ज़िट करता है"],["AI will analyse","AI विश्लेषण करेगा"],["AI will wait","AI इंतज़ार करेगा"],["AI pauses","AI रुक जाता है"],["AI stops automatically","AI अपने-आप रुक जाता है"],["AI decision","AI निर्णय"],["AI mode","AI मोड"],["AI reason","AI कारण"],["AI signal","AI संकेत"],["AI confidence","AI विश्वास"],["AI markets","AI मार्केट"],["AI workspace","AI वर्कस्पेस"],["AI Guide","AI गाइड"],
 ["paper trading","पेपर ट्रेडिंग"],["paper trade","पेपर ट्रेड"],["paper account","पेपर अकाउंट"],["paper balance","पेपर बैलेंस"],["paper position","पेपर पोज़िशन"],["paper order","पेपर ऑर्डर"],["paper mode","पेपर मोड"],["virtual capital","वर्चुअल पूँजी"],["virtual balance","वर्चुअल बैलेंस"],["virtual amount","वर्चुअल राशि"],["real money","असली पैसा"],["real funds","असली फंड"],["exchange connection","एक्सचेंज कनेक्शन"],["exchange order","एक्सचेंज ऑर्डर"],
 ["risk engine","जोखिम इंजन"],["risk management","जोखिम प्रबंधन"],["risk per trade","हर ट्रेड का जोखिम"],["risk limit","जोखिम सीमा"],["risk status","जोखिम स्थिति"],["daily loss limit","दैनिक नुकसान सीमा"],["daily maximum loss","अधिकतम दैनिक नुकसान"],["loss limit","नुकसान सीमा"],["safety limits","सुरक्षा सीमाएँ"],["safety settings","सुरक्षा सेटिंग्स"],["safety rules","सुरक्षा नियम"],["safety pause","सुरक्षा रोक"],["stop-loss protected","Stop Loss से सुरक्षित"],["take-profit","Take Profit"],["stop-loss","Stop Loss"],["stop loss","Stop Loss"],["take profit","Take Profit"],
 ["open positions","खुली पोज़िशन"],["open position","खुली पोज़िशन"],["closed positions","बंद पोज़िशन"],["position size","पोज़िशन राशि"],["current price","मौजूदा कीमत"],["entry price","एंट्री कीमत"],["exit price","एग्ज़िट कीमत"],["market price","मार्केट कीमत"],["current value","मौजूदा मूल्य"],["available balance","उपलब्ध बैलेंस"],["account value","अकाउंट मूल्य"],["account values","अकाउंट मूल्य"],["trading capital","ट्रेडिंग पूँजी"],["allocated capital","लगाई गई पूँजी"],["maximum planned risk","अधिकतम नियोजित जोखिम"],
 ["Trade history","ट्रेड इतिहास"],["trade details","ट्रेड विवरण"],["Trade safely","सुरक्षित ट्रेड करें"],["Trade smarter","समझदारी से ट्रेड करें"],["trading terms","ट्रेडिंग शब्द"],["market data","मार्केट डेटा"],["market scanner","मार्केट स्कैनर"],["market mood","मार्केट का रुझान"],["market conditions","मार्केट स्थिति"],["market showed","मार्केट ने क्या दिखाया"],["markets selected","मार्केट चुने गए"],["markets to watch","देखने के लिए मार्केट"],["crypto markets","क्रिप्टो मार्केट"],["crypto assets","क्रिप्टो एसेट"],
 ["Settings & risk","सेटिंग्स और जोखिम"],["Save changes","बदलाव सेव करें"],["Reset defaults","डिफ़ॉल्ट रीसेट करें"],["Change preference","पसंद बदलें"],["Language preferences","भाषा की पसंद"],["Display preferences","डिस्प्ले की पसंद"],["Choose your experience","अपना अनुभव चुनें"],["Choose automatically","अपने-आप चुनें"],["Search country or language","देश या भाषा खोजें"],["stored on this device","इस डिवाइस पर सेव है"],["saved on this device","इस डिवाइस पर सेव है"],
 ["What happens next","आगे क्या होगा"],["What the market showed","मार्केट ने क्या दिखाया"],["Why this decision","यह निर्णय क्यों"],["Why AI took this trade","AI ने यह ट्रेड क्यों लिया"],["Every AI decision explained","हर AI निर्णय समझाया गया"],["transparent AI decisions","स्पष्ट AI निर्णय"],["hard safety limits","कड़ी सुरक्षा सीमाएँ"],["full control","पूरा नियंत्रण"],["strict limits","कड़ी सीमाएँ"],["within limits","सीमा के अंदर"],["before every decision","हर निर्णय से पहले"],["before every trade","हर ट्रेड से पहले"],["before execution","एक्ज़ीक्यूशन से पहले"],
 ["Create paper account","पेपर अकाउंट बनाएँ"],["Create secure account","सुरक्षित अकाउंट बनाएँ"],["Start trading safely","सुरक्षित ट्रेडिंग शुरू करें"],["Reset your password","अपना पासवर्ड रीसेट करें"],["Back to sign in","साइन इन पर वापस"],["Sign in","साइन इन"],["Full name","पूरा नाम"],["Your name","आपका नाम"],["Enter your password","अपना पासवर्ड डालें"],["Create a strong password","मज़बूत पासवर्ड बनाएँ"],["Check your email","अपना ईमेल देखें"],
 ["No bots running yet","अभी कोई बॉट नहीं चल रहा"],["Active paper bots","सक्रिय पेपर बॉट"],["Build your first bot","अपना पहला बॉट बनाएँ"],["Edit strategy","रणनीति बदलें"],["Last decision","पिछला निर्णय"],["Open safety settings","सुरक्षा सेटिंग्स खोलें"],["Review Testnet positions","Testnet पोज़िशन देखें"],["Emergency stop","आपातकालीन रोक"],["Stop all new entries","सभी नई एंट्री रोकें"],["Protective exits","सुरक्षित एग्ज़िट"],["New entries","नई एंट्री"],
 ["No markets found","कोई मार्केट नहीं मिला"],["No Testnet orders yet","अभी कोई Testnet ऑर्डर नहीं"],["No real exchange order was submitted","कोई असली एक्सचेंज ऑर्डर नहीं भेजा गया"],["No trading rules were changed","कोई ट्रेडिंग नियम नहीं बदला"],["No crypto is touched","कोई असली क्रिप्टो इस्तेमाल नहीं होता"],["No real crypto is touched","कोई असली क्रिप्टो इस्तेमाल नहीं होता"],["Illustrative market data","उदाहरण मार्केट डेटा"],["guarantee future returns","भविष्य के रिटर्न की गारंटी नहीं"],["does not guarantee profit","मुनाफ़े की गारंटी नहीं देता"],
 ["View AI activity","AI गतिविधि देखें"],["View related AI activity","संबंधित AI गतिविधि देखें"],["View updated terminal","अपडेटेड टर्मिनल देखें"],["Open live analysis","लाइव विश्लेषण खोलें"],["Open chart","चार्ट खोलें"],["Open safety settings","सुरक्षा सेटिंग्स खोलें"],["Return to terminal","टर्मिनल पर वापस"],["Keep position open","पोज़िशन खुली रखें"],["Close full","पूरी तरह बंद करें"],["Close position","पोज़िशन बंद करें"],["Confirm full simulated exit","पूरी सिम्युलेटेड एग्ज़िट की पुष्टि करें"],
 ["Current automation","मौजूदा ऑटोमेशन"],["Current demo price","मौजूदा डेमो कीमत"],["Current paper value","मौजूदा पेपर मूल्य"],["Live public price","लाइव सार्वजनिक कीमत"],["Latest available price","नवीनतम उपलब्ध कीमत"],["Started with","शुरुआत"],["Updated paper balance","अपडेटेड पेपर बैलेंस"],["Returned allocation","वापस मिली राशि"],["Realised paper P&L","हुआ पेपर लाभ/हानि"],["Unrealized paper P&L","अनुमानित पेपर लाभ/हानि"],
 ["Recommended","सुझाया गया"],["Advanced","उन्नत"],["Protected","सुरक्षित"],["Blocked","रुका हुआ"],["Passed","पास"],["Active","सक्रिय"],["Paused","रुका हुआ"],["Ready","तैयार"],["Open","खुला"],["Closed","बंद"],["Today","आज"],["tomorrow","कल"],["Settings","सेटिंग्स"],["Safety","सुरक्षा"],["History","इतिहास"],["Portfolio","पोर्टफोलियो"],["Profile","प्रोफ़ाइल"],["Analytics","विश्लेषण"],["Wallet","वॉलेट"],["Guide","गाइड"],["Balance","बैलेंस"],["Amount","राशि"],["Price","कीमत"],["Confidence","विश्वास"],["Decision","निर्णय"],["Reason","कारण"],["Status","स्थिति"],["Market","मार्केट"],["Capital","पूँजी"],["Limits","सीमाएँ"],["Continue","जारी रखें"],["Cancel","रद्द करें"],["Close","बंद करें"],["Save","सेव करें"],["Search","खोजें"],["Review","समीक्षा"],["Change","बदलें"],["Create","बनाएँ"],["Edit","बदलें"],["Manage","मैनेज करें"]
].sort((a,b)=>b[0].length-a[0].length) as Array<[string,string]>;

const originalText=new WeakMap<Text,string>(),translatedText=new WeakMap<Text,string>(),originalAttrs=new WeakMap<Element,Map<string,string>>();
const escape=(value:string)=>value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");
function hindi(value:string){
 const lead=value.match(/^\s*/)?.[0]||"",trail=value.match(/\s*$/)?.[0]||"",core=value.trim();
 if(!core)return value;
 let output=exact[core]||core;
 if(output===core)for(const [from,to] of phrases)output=output.replace(new RegExp(escape(from),"gi"),to);
 return lead+output+trail;
}
function translateNode(node:Text,language:Language,restore=false){
 const current=node.nodeValue||"",last=translatedText.get(node);
 if(language==="HI"){
  if(current===last)return;
  if(!originalText.has(node)||current!==last)originalText.set(node,current);
  const next=hindi(originalText.get(node)||current);translatedText.set(node,next);if(current!==next)node.nodeValue=next;
 }else{const source=originalText.get(node);if(restore&&source!==undefined&&current!==source)node.nodeValue=source;else if(!restore)originalText.set(node,current);translatedText.delete(node)}
}
function translateElement(root:ParentNode,language:Language,restore=false){
 const elements=root instanceof Element?[root,...Array.from(root.querySelectorAll("*"))]:Array.from(root.querySelectorAll("*"));
 for(const element of elements){
  if(element.matches("script,style,noscript,[data-no-translate]")||element.closest("[data-no-translate]"))continue;
  if(element.tagName==="OPTION"&&!element.hasAttribute("value"))element.setAttribute("value",element.textContent||"");
  for(const attr of ["placeholder","title","aria-label"]){const current=element.getAttribute(attr);if(!current)continue;let saved=originalAttrs.get(element);if(!saved){saved=new Map();originalAttrs.set(element,saved)}if(language==="HI"){if(!saved.has(attr))saved.set(attr,current);element.setAttribute(attr,hindi(saved.get(attr)||current))}else if(restore&&saved.has(attr))element.setAttribute(attr,saved.get(attr)||"");else saved.set(attr,current)}
 }
 const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node=walker.nextNode();while(node){const text=node as Text,parent=text.parentElement;if(parent&&!parent.closest("script,style,noscript,[data-no-translate]"))translateNode(text,language,restore);node=walker.nextNode()}
}

export default function GlobalLanguage(){
 const [language,setLanguage]=useState<Language>("EN");
 useEffect(()=>{
  let active:Language=window.localStorage.getItem("chatonyou-language")==="HI"?"HI":"EN",working=false,started=false;
  const apply=(next:Language)=>{active=next;setLanguage(next);document.documentElement.lang=next==="HI"?"hi":"en";document.body.classList.toggle("global-hi",next==="HI");working=true;translateElement(document.body,next,true);working=false};
  const observer=new MutationObserver(records=>{if(working)return;working=true;for(const record of records){if(record.type==="characterData")translateNode(record.target as Text,active);for(const added of Array.from(record.addedNodes)){if(added.nodeType===Node.TEXT_NODE)translateNode(added as Text,active);else if(added instanceof Element)translateElement(added,active)}}working=false});
  const start=()=>{if(started)return;started=true;apply(active);observer.observe(document.body,{subtree:true,childList:true,characterData:true})};
  const onLanguage=(event:Event)=>{const requested=(event as CustomEvent<Language>).detail;active=requested==="HI"?"HI":"EN";if(started)apply(active);else setLanguage(active)};
  const timer=window.setTimeout(start,500);window.addEventListener("chatonyou-language-change",onLanguage);return()=>{window.clearTimeout(timer);observer.disconnect();window.removeEventListener("chatonyou-language-change",onLanguage)};
 },[]);
 const toggle=()=>{const next:Language=language==="HI"?"EN":"HI";window.localStorage.setItem("chatonyou-language",next);window.dispatchEvent(new CustomEvent("chatonyou-language-change",{detail:next}))};
 return <button data-no-translate className="global-language-toggle" onClick={toggle} aria-label={language==="HI"?"Switch to English":"हिन्दी में देखें"}><span>文</span>{language==="HI"?"EN":"हिंदी"}</button>;
}
