"use client";

import { useEffect,useMemo,useState } from "react";
import { useBinanceMarket } from "../useBinanceMarket";

type SavedTrade={id:string;asset:string;side:"BUY"|"SELL";amountPaise:number;entryPrice:number;stopPrice:number;targetPrice:number;status:string;createdAt:number};
const inr=(n:number)=>new Intl.NumberFormat("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
const usd=(n:number)=>`$${new Intl.NumberFormat("en-US",{minimumFractionDigits:2,maximumFractionDigits:2}).format(n)}`;
const colors:Record<string,string>={BTC:"#f5a623",ETH:"#8293ff",SOL:"#92ffc7",BNB:"#f2d354"};

export default function ExitPosition(){
 const [position,setPosition]=useState<SavedTrade|null>(null),[confirmed,setConfirmed]=useState(false),[stage,setStage]=useState<"loading"|"review"|"closing"|"done"|"error">("loading"),[error,setError]=useState(""),[result,setResult]=useState<{pnlPaise:number;balancePaise:number;exitPrice:number}|null>(null);
 const asset=position?.asset||"BTC",{tickers,status}=useBinanceMarket(asset),livePrice=tickers[asset+"USDT"]?.price;
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get("id");if(!id){setError("The paper-position ID is missing.");setStage("error");return}fetch("/api/trades",{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then(data=>{const found=(data.trades||[]).find((item:SavedTrade)=>item.id===id&&item.status==="open");if(!found)throw new Error("The open paper position was not found.");setPosition(found);setStage("review")}).catch(reason=>{setError(reason instanceof Error?reason.message:"The position could not be loaded.");setStage("error")})},[]);
 const exitPrice=livePrice||position?.entryPrice||0;
 const pnlPaise=useMemo(()=>{if(!position||!exitPrice)return 0;const direction=position.side==="SELL"?-1:1;return Math.max(-position.amountPaise,Math.round(position.amountPaise*((exitPrice-position.entryPrice)/position.entryPrice)*direction))},[position,exitPrice]);
 const pnl=pnlPaise/100,amount=(position?.amountPaise||0)/100,percent=position?((exitPrice-position.entryPrice)/position.entryPrice)*100*(position.side==="SELL"?-1:1):0;
 async function close(){if(!position||!confirmed)return;setStage("closing");setError("");try{const response=await fetch("/api/trades",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"close",id:position.id})});const data=await response.json();if(!response.ok)throw new Error(data.error||"The paper position could not be closed.");setResult(data);setStage("done");if("Notification" in window&&Notification.permission==="granted")new Notification(`${position.asset} paper position closed`,{body:`Realised P&L ${data.pnlPaise>=0?"+":"-"}₹${Math.abs(data.pnlPaise/100).toFixed(2)}`})}catch(reason){setError(reason instanceof Error?reason.message:"The paper position could not be closed.");setStage("review")}}
 if(stage==="loading")return <main className="system-state-shell"><a className="terminal-logo" href="/"><img src="/chatonyou-logo.png" alt="ChatOnYou"/><b>TRADE</b></a><section><div className="system-loader"><i/><i/><i/></div><span>SAVED PAPER POSITION</span><h1>Loading the position.</h1><p>Synchronizing the account record and live public market price.</p></section></main>;
 if(stage==="error"||!position)return <main className="system-state-shell"><a className="terminal-logo" href="/"><img src="/chatonyou-logo.png" alt="ChatOnYou"/><b>TRADE</b></a><section><div className="system-icon danger">!</div><span>PAPER EXIT</span><h1>This position is not open.</h1><p>{error}</p><a className="system-primary" href="/trade">Return to the trading terminal <b>→</b></a></section></main>;
 return <main className="exit-shell"><header className="order-top"><a className="terminal-logo" href="/"><img src="/chatonyou-logo.png" alt="ChatOnYou"/><b>TRADE</b></a><span><i/> PAPER MODE · {status.toUpperCase()}</span><a href="/trade">×</a></header><div className="exit-grid">
  <section className="exit-position-card"><header><div><i style={{background:colors[position.asset]||"#91a3ff"}}>{position.asset[0]}</i><span><b>{position.asset}/USDT</b><small>{position.side} · Saved paper position</small></span></div><em>OPEN</em></header><div className="exit-profit"><span>UNREALIZED PAPER P&amp;L</span><strong className={pnl>=0?"positive":"history-negative"}>{pnl>=0?"+":"-"}₹{inr(Math.abs(pnl))}</strong><b>{percent>=0?"+":""}{percent.toFixed(2)}%</b><i><em style={{width:`${Math.min(100,Math.max(4,50+percent*8))}%`}}/></i></div><div className="exit-position-stats"><span>Entry<b>{usd(position.entryPrice)}</b></span><span>Live public price<b>{usd(exitPrice)}</b></span><span>Allocated capital<b>₹{inr(amount)}</b></span><span>Opened<b>{new Date(position.createdAt).toLocaleString("en-IN",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"})}</b></span></div><section className="exit-mini-chart"><div className="exit-chart-label"><span>ENTRY <b>{usd(position.entryPrice)}</b></span><span>MARK <b>{usd(exitPrice)}</b></span></div><div className="exit-chart-line"><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/></div><div className="exit-level stop"><span>SL</span><b>{usd(position.stopPrice)}</b></div><div className="exit-level target"><span>TP</span><b>{usd(position.targetPrice)}</b></div></section><section className="exit-ai-view"><header><span>✦ SETTLEMENT CHECK</span><b className="hold">FULL EXIT</b></header><p>The simulated P&amp;L is calculated at the live public price. The allocation and final result settle back into the saved paper balance.</p><div><span><i>✓</i>Authenticated position</span><span><i>◇</i>No exchange order</span></div></section><p className="exit-illustrative">Binance public market price · Paper settlement only · No real funds</p></section>
  {stage==="done"&&result?<section className="exit-complete"><div><i>✓</i></div><span>PAPER SETTLEMENT SAVED</span><h1>Position closed.</h1><p>The {position.asset}/USDT paper position moved to history and the saved balance was updated.</p><article><span>Realised paper P&amp;L<b className={result.pnlPaise>=0?"positive":"history-negative"}>{result.pnlPaise>=0?"+":"-"}₹{inr(Math.abs(result.pnlPaise/100))}</b></span><span>Returned allocation<b>₹{inr(amount)}</b></span><span>Server exit price<b>{usd(result.exitPrice)}</b></span><span>Updated paper balance<b>₹{inr(result.balancePaise/100)}</b></span></article><a href="/trade">View updated terminal <span>→</span></a><a href="/trade/history">Open saved history</a><small>No real exchange order was submitted.</small></section>:<section className="exit-review"><span>PERSISTENT PAPER EXIT</span><h1>Close this position.<br/>Settle the result.</h1><p>The full position closes at the current public price. No real crypto is touched.</p><section className="exit-impact"><header>SETTLEMENT PREVIEW <span>{status==="live"?"Live Binance price":"Latest available price"}</span></header><div><span>Allocated capital<b>₹{inr(amount)}</b></span><span>Preview price<b>{usd(exitPrice)}</b></span><span>Estimated paper P&amp;L<b className={pnl>=0?"positive":"history-negative"}>{pnl>=0?"+":"-"}₹{inr(Math.abs(pnl))}</b></span><span>Estimated balance credit<b>₹{inr(Math.max(0,amount+pnl))}</b></span></div><footer><i>◇</i><span><b>Server-verified settlement</b><small>The server rechecks the live public price before saving this paper exit.</small></span></footer></section><label className="exit-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><i>✓</i><span><b>Confirm full simulated exit</b><small>I understand this only closes a saved paper position.</small></span></label>{error&&<p className="order-api-error">{error}</p>}<button className="exit-button" disabled={!confirmed||stage==="closing"||!exitPrice} onClick={close}>{stage==="closing"?<><i className="order-spinner"/>Saving settlement…</>:<>Close full {position.asset} position <span>→</span></>}</button>{!confirmed&&<small className="exit-help">Select the paper-exit confirmation to continue.</small>}<a className="exit-cancel" href="/trade">Keep position open</a></section>}
 </div></main>;
}
