"use client";
import { useCallback, useEffect, useState } from "react";

type Check={id:string;label:string;ok:boolean;detail:string};
type Signal={asset:string;signal:"BUY"|"SELL"|"NO TRADE";confidence:number;entry:number;stopLoss:number|null;takeProfit:number|null;trend:string;riskPct:number;reasons:string[]};
type Order={id:string;asset:string;source:string;status:string;binanceStatus:string;quoteAmount:number;quantity:number;entryPrice:number;stopPrice:number;targetPrice:number;exitPrice:number|null;pnlQuote:number;confidence:number;error:string|null;createdAt:number};
type Event={id:string;category:string;action:string;detail:string;createdAt:number};
const assets=[{id:"BTC",symbol:"₿",color:"#f5a623"},{id:"ETH",symbol:"◆",color:"#8293ff"},{id:"SOL",symbol:"S",color:"#65efad"},{id:"BNB",symbol:"B",color:"#f1d26a"}];
const usd=(value:number,digits=2)=>new Intl.NumberFormat("en-US",{minimumFractionDigits:digits,maximumFractionDigits:digits}).format(value);

export default function TestnetCommand(){
 const [asset,setAsset]=useState("BTC"),[amount,setAmount]=useState(10),[signals,setSignals]=useState<Record<string,Signal>>({}),[checks,setChecks]=useState<Check[]>([]),[connected,setConnected]=useState(false),[canTrade,setCanTrade]=useState(false),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[orders,setOrders]=useState<Order[]>([]),[events,setEvents]=useState<Event[]>([]),[emergency,setEmergency]=useState(false),[auto,setAuto]=useState(false),[summary,setSummary]=useState({open:0,closed:0,pnlQuote:0,winRate:0}),[explanation,setExplanation]=useState<{summary:string;bullets:string[];guardrail:string}|null>(null),[autoLog,setAutoLog]=useState("AI Auto is waiting for permission."),[tab,setTab]=useState<"positions"|"activity"|"safety">("positions");
 const signal=signals[asset],allowed=checks.length>0&&checks.every(item=>item.ok);
 const loadAccount=useCallback(async()=>{const [exchangeResponse,ordersResponse]=await Promise.all([fetch("/api/exchange",{cache:"no-store"}),fetch("/api/testnet/orders?sync=1",{cache:"no-store"})]);if(exchangeResponse.ok){const data=await exchangeResponse.json();setConnected(Boolean(data.connected));setCanTrade(Boolean(data.connection?.canTrade))}if(ordersResponse.ok){const data=await ordersResponse.json();setOrders(data.orders||[]);setEvents(data.events||[]);setEmergency(Boolean(data.safety?.emergencyStop));setAuto(Boolean(data.safety?.autoTestnetEnabled));setSummary(data.summary||{open:0,closed:0,pnlQuote:0,winRate:0})}},[]);
 const scanSignals=useCallback(async()=>{const values=await Promise.all(assets.map(async item=>{const response=await fetch(`/api/signals?asset=${item.id}`,{cache:"no-store"});if(!response.ok)throw new Error("Live quant scan unavailable");return response.json() as Promise<Signal>}));setSignals(Object.fromEntries(values.map(item=>[item.asset,item])));return values},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>{loadAccount().catch(()=>setMessage("Saved Testnet status could not be loaded."));scanSignals().catch(()=>setMessage("Live quant scan is temporarily unavailable."))},0);return()=>window.clearTimeout(timer)},[loadAccount,scanSignals]);
 useEffect(()=>{fetch(`/api/ai/explain?asset=${asset}`,{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then(setExplanation).catch(()=>setExplanation(null))},[asset]);
 useEffect(()=>{const timer=window.setTimeout(()=>{fetch("/api/testnet/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"validate",asset,quoteAmount:amount})}).then(async r=>{const data=await r.json();setChecks(data.checks||[]);if(!r.ok&&data.error)setMessage(data.error)}).catch(()=>setChecks([]))},300);return()=>window.clearTimeout(timer)},[asset,amount,orders,emergency,connected]);
 const execute=async()=>{if(!allowed||!confirmed)return;setBusy(true);setMessage("");try{const response=await fetch("/api/testnet/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"manual",asset,quoteAmount:amount,confirmed:true})}),data=await response.json();if(!response.ok)throw new Error(data.error||"Testnet order blocked");setMessage(data.warning?`Entry placed · Protection warning: ${data.warning}`:`Protected Testnet order ${data.id} placed.`);setConfirmed(false);await loadAccount()}catch(reason){setMessage(reason instanceof Error?reason.message:"Testnet order failed")}finally{setBusy(false)}};
 const closeOrder=async(id:string)=>{setBusy(true);setMessage("");try{const response=await fetch("/api/testnet/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"close",id})}),data=await response.json();if(!response.ok)throw new Error(data.error||"Close failed");setMessage(`Position closed · ${data.pnlQuote>=0?"+":""}${Number(data.pnlQuote).toFixed(4)} USDT`);await loadAccount()}catch(reason){setMessage(reason instanceof Error?reason.message:"Close failed")}finally{setBusy(false)}};
 const setAutoMode=async(enabled:boolean)=>{setBusy(true);setMessage("");try{const response=await fetch("/api/safety",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"auto",enabled})}),data=await response.json();if(!response.ok)throw new Error(data.error);setAuto(enabled);setEmergency(false);setAutoLog(enabled?"AI Auto enabled · first protected scan starting.":"AI Auto disabled manually.")}catch(reason){setMessage(reason instanceof Error?reason.message:"Auto mode update failed")}finally{setBusy(false)}};
 const emergencyAction=async(stop:boolean)=>{setBusy(true);try{const response=await fetch("/api/safety",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(stop?{action:"stop"}:{action:"resume",confirmed:true})}),data=await response.json();if(!response.ok)throw new Error(data.error);setEmergency(stop);if(stop)setAuto(false);setMessage(stop?"Emergency stop active · all new entries blocked.":"Safety stop manually cleared · Auto remains OFF.");await loadAccount()}catch(reason){setMessage(reason instanceof Error?reason.message:"Safety control failed")}finally{setBusy(false)}};
 const runAuto=useCallback(async()=>{if(!auto||emergency||busy)return;try{const values=await scanSignals(),candidate=values.filter(item=>item.signal==="BUY").sort((a,b)=>b.confidence-a.confidence)[0];if(!candidate){setAutoLog("NO TRADE · No Spot BUY signal passed the quant engine.");return}const response=await fetch("/api/testnet/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"auto",asset:candidate.asset,quoteAmount:Math.min(10,amount)})}),data=await response.json();setAutoLog(response.ok?`AI protected ${candidate.asset} entry placed · ${data.id}`:`BLOCKED · ${data.error||"Risk rules denied the entry"}`);if(response.ok)await loadAccount()}catch{setAutoLog("Scan unavailable · no order created.")}},[auto,emergency,busy,scanSignals,amount,loadAccount]);
 useEffect(()=>{if(!auto||emergency)return;const first=window.setTimeout(runAuto,800),timer=window.setInterval(runAuto,30000);return()=>{window.clearTimeout(first);window.clearInterval(timer)}},[auto,emergency,runAuto]);
 const selected=assets.find(item=>item.id===asset)!;
 const riskCheck=checks.find(item=>item.id==="risk"),riskUse=!riskCheck?"Waiting":riskCheck.ok?"Within limit":"Blocked";
 return <main className="testnet-shell">
  <header className="testnet-top"><a className="terminal-logo" href="/"><img src="/chatonyou-logo.png" alt="ChatOnYou"/><b>TRADE</b></a><div><i/> BINANCE SPOT TESTNET</div><nav><a href="/trade/wallet">Connection</a><a href="/trade">Terminal</a><a href="/trade/settings">Risk settings</a></nav><a className="testnet-profile" href="/trade/profile">NS</a></header>
  <section className="testnet-main">
   <div className="testnet-hero"><div><span>AI EXECUTION COMMAND</span><h1>AI finds the trade.<br/><em>Risk rules control it.</em></h1><p>Real Binance matching-engine experience with virtual Testnet assets. Every entry is checked, recorded and protected before AI can continue.</p></div><div className="testnet-health"><span><i className={connected?"ok":""}/><b>Testnet connection</b><em>{connected?"Connected":"Required"}</em></span><span><i className={canTrade?"ok":""}/><b>Spot permission</b><em>{canTrade?"Verified":"Enable"}</em></span><span><i className={!emergency?"ok":"danger"}/><b>Risk engine</b><em>{emergency?"Stopped":"Protected"}</em></span></div></div>
   {!connected||!canTrade?<section className="testnet-connect-gate"><i>◇</i><div><span>ONE SAFE STEP LEFT</span><h2>{connected?"Enable Spot trading on the Testnet key":"Connect Binance Spot Testnet"}</h2><p>No order can leave ChatOnYou until the encrypted Testnet connection and trading permission are verified.</p></div><a href="/trade/wallet">Open secure connection <b>→</b></a></section>:null}
   <section className="testnet-market-strip">{assets.map(item=>{const value=signals[item.id];return <button className={asset===item.id?"active":""} onClick={()=>{setAsset(item.id);setMessage("")}} key={item.id}><i style={{background:item.color}}>{item.symbol}</i><span><b>{item.id}/USDT</b><small>{value?`$${usd(value.entry,item.id==="BTC"||item.id==="ETH"?2:4)}`:"Scanning…"}</small></span><em className={(value?.signal||"wait").toLowerCase().replace(" ","-")}>{value?.signal||"WAIT"}<small>{value?.confidence||0}%</small></em></button>})}</section>
   <section className="testnet-workspace">
    <article className="testnet-order-card"><header><div><i style={{background:selected.color}}>{selected.symbol}</i><span><b>{asset}/USDT</b><small>Spot Testnet · MARKET BUY</small></span></div><em>{signal?.signal||"SCANNING"}</em></header><div className="testnet-price"><span>QUANT ENTRY</span><strong>${signal?usd(signal.entry,asset==="BTC"||asset==="ETH"?2:4):"—"}</strong><small>{signal?.trend||"Waiting"} · {signal?.confidence||0}% confidence</small></div><label className="testnet-amount">Testnet allocation <small>10–250 virtual USDT</small><div><b>₮</b><input type="number" min="10" max="250" step="5" value={amount} onChange={e=>setAmount(Number(e.target.value))}/><span>USDT</span></div><nav>{[10,25,50,100].map(value=><button className={amount===value?"active":""} onClick={()=>setAmount(value)} key={value}>{value} USDT</button>)}</nav></label><div className="testnet-levels"><span><small>STOP LOSS</small><b>${signal?.stopLoss?usd(signal.stopLoss,asset==="BTC"||asset==="ETH"?2:4):"—"}</b></span><span><small>TAKE PROFIT</small><b>${signal?.takeProfit?usd(signal.takeProfit,asset==="BTC"||asset==="ETH"?2:4):"—"}</b></span><span><small>RISK STATUS</small><b>{riskUse}</b></span></div><div className="testnet-checks">{checks.map(item=><span key={item.id}><i className={item.ok?"ok":""}>{item.ok?"✓":"!"}</i><b>{item.label}<small>{item.detail}</small></b></span>)}</div><label className="testnet-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><i>✓</i><span><b>I approve this virtual Testnet order</b><small>This uses no real money and may still produce a simulated loss.</small></span></label>{message?<p className="testnet-message">{message}</p>:null}<button className="testnet-execute" disabled={!allowed||!confirmed||busy||!connected||!canTrade} onClick={execute}>{busy?"Risk engine working…":`Execute protected ${asset} Testnet BUY`} <span>→</span></button></article>
    <aside className="testnet-ai-card"><header><span><i>✦</i> AI REASONING</span><em>{signal?.confidence||0}%</em></header><h2>{signal?.signal==="BUY"?"Controlled opportunity detected.":signal?.signal==="SELL"?"Spot entry blocked.":"AI is choosing patience."}</h2><p>{explanation?.summary||"Live candles and risk rules are being analysed."}</p><div>{(explanation?.bullets||signal?.reasons||[]).slice(0,5).map((reason,index)=><span key={reason}><i>{index+1}</i><b>{reason}</b></span>)}</div><footer><i>◇</i><span><b>Deterministic guardrail</b><small>{explanation?.guardrail||"No order can bypass saved risk limits."}</small></span></footer><small>Explanation layer is API-ready. Quant and risk decisions remain deterministic.</small></aside>
   </section>
   <section className="testnet-auto-panel"><div><span>AI AUTO · TESTNET</span><h2>Continuous protected execution</h2><p>While this page is open, AI scans every 30 seconds. It can only open one Spot BUY per asset, inside your saved confidence, risk and daily-loss limits.</p></div><section><div className="auto-pulse"><i className={auto&&!emergency?"on":""}>✦</i><span><b>{emergency?"Emergency stop active":auto?"AI Auto is watching":"AI Auto is off"}</b><small>{autoLog}</small></span></div><button disabled={busy||emergency||!connected||!canTrade} className={auto?"on":""} onClick={()=>setAutoMode(!auto)}><i/>{auto?"ON":"OFF"}</button></section><a href="/trade/settings">Edit hard limits →</a></section>
   <section className="testnet-records"><header><div><span>LIVE ACCOUNT RECORD</span><h2>Orders, activity &amp; safety</h2></div><nav>{(["positions","activity","safety"] as const).map(item=><button className={tab===item?"active":""} onClick={()=>setTab(item)} key={item}>{item}</button>)}</nav><button onClick={()=>loadAccount()}>↻ Sync Binance</button></header>
    {tab==="positions"?<div className="testnet-orders"><div className="testnet-order-label"><span>MARKET</span><span>SOURCE</span><span>ENTRY</span><span>PROTECTION</span><span>STATUS</span><span>P&amp;L</span><span/></div>{orders.length?orders.map(item=><article key={item.id}><span><b>{item.asset}/USDT</b><small>{new Date(item.createdAt).toLocaleString("en-IN")}</small></span><em>{item.source==="auto"?"AI AUTO":"MANUAL"}</em><span><b>{item.entryPrice?`$${usd(item.entryPrice,item.asset==="BTC"||item.asset==="ETH"?2:4)}`:"—"}</b><small>{item.quoteAmount.toFixed(2)} USDT</small></span><span><b>SL ${usd(item.stopPrice,item.asset==="BTC"||item.asset==="ETH"?2:4)}</b><small>TP ${usd(item.targetPrice,item.asset==="BTC"||item.asset==="ETH"?2:4)}</small></span><strong className={item.status}>{item.status}</strong><b className={item.pnlQuote>=0?"positive":"negative"}>{item.status==="closed"?`${item.pnlQuote>=0?"+":""}${item.pnlQuote.toFixed(4)} ₮`:"—"}</b>{["open","protected","unprotected"].includes(item.status)?<button disabled={busy} onClick={()=>closeOrder(item.id)}>Close</button>:<i>—</i>}</article>):<div className="testnet-empty"><i>↗</i><h3>No Testnet orders yet</h3><p>When a live BUY signal passes every guardrail, the protected execution button becomes available.</p></div>}</div>:null}
    {tab==="activity"?<div className="testnet-events">{events.length?events.map(item=><article key={item.id}><i>{item.category==="safety"?"◇":item.category==="risk"?"!":"↗"}</i><span><b>{item.action.replaceAll("_"," ")}</b><small>{item.detail}</small></span><time>{new Date(item.createdAt).toLocaleString("en-IN")}</time></article>):<div className="testnet-empty"><h3>Activity will appear here</h3><p>Entries, exits, blocks and safety changes are saved to your account.</p></div>}</div>:null}
    {tab==="safety"?<div className="testnet-safety"><article><span>TODAY&apos;S TESTNET P&amp;L</span><strong className={summary.pnlQuote>=0?"positive":"negative"}>{summary.pnlQuote>=0?"+":""}{summary.pnlQuote.toFixed(4)} USDT</strong><small>{summary.closed} closed · {summary.winRate.toFixed(1)}% win rate</small></article><article><span>OPEN POSITIONS</span><strong>{summary.open}</strong><small>Every protected position uses OCO exits</small></article><article><span>EMERGENCY CONTROL</span><strong>{emergency?"STOPPED":"READY"}</strong><small>{emergency?"New entries are blocked":"Protective exits remain active"}</small></article><div><p>{emergency?"Manual resume keeps AI Auto OFF until you approve it again.":"Emergency stop blocks paper and Testnet entries immediately. Existing protective exits remain on Binance Testnet."}</p><button disabled={busy} className={emergency?"resume":"stop"} onClick={()=>emergencyAction(!emergency)}>{emergency?"Resume manual control":"Activate emergency stop"}</button></div></div>:null}
   </section>
   <section className="testnet-live-gate"><div><span>REAL-MONEY LAUNCH GATE</span><h2>Live trading stays locked.</h2><p>Production keys, two-step verification, regulatory review, tested drawdown history and a separate explicit owner approval are required before any real exchange order can exist.</p></div><div><span><i>✓</i>Paper strategy</span><span><i>✓</i>Spot Testnet engine</span><span><i>✓</i>Risk &amp; emergency controls</span><span className="locked"><i>×</i>Real-money execution</span></div><a href="/trade/live">View launch checklist <b>→</b></a></section>
   <p className="ai-data-note">Binance Spot Testnet uses virtual assets · No profit guarantee · No futures, leverage, withdrawals or unrestricted exchange access</p>
  </section>
  <nav className="ai-mobile-nav"><a href="/trade"><i>↗</i>Trade</a><a className="active" href="/trade/testnet"><i>◇</i>Testnet</a><a href="/trade/auto"><i>✦</i>Auto</a><a href="/trade/wallet"><i>W</i>Wallet</a><a href="/trade/settings"><i>⚙</i>Safety</a></nav>
 </main>
}
