"use client";
import { useEffect,useMemo,useState } from "react";

type Range="7D"|"30D"|"ALL";
type Market={coin:string;trades:number;win:number;pnl:string;color?:string};
type AnalyticsData={balance:string;startingBalance:string;allocated:string;profit:string;return:string;trades:number;wins:number;losses:number;win:string;drawdown:string;points:string;labels:string[];markets:Market[];decisions:number;noTrades:number;open:number;highConfidencePct:number;targetReachedPct:number;hours:number[];risk:{score:number;coverage:number;maxPositions:number;openPositions:number;maxRiskPct:number;dailyLossPct:number}};
const emptyData:AnalyticsData={balance:"₹0",startingBalance:"₹0",allocated:"₹0",profit:"₹0",return:"0.00%",trades:0,wins:0,losses:0,win:"0%",drawdown:"-0.00%",points:"0,130 66,130 132,130 198,130 264,130 330,130 396,130 462,130 528,130 594,130 660,130",labels:["Start","Midpoint","Today"],markets:[],decisions:0,noTrades:0,open:0,highConfidencePct:0,targetReachedPct:0,hours:Array.from({length:12},()=>0),risk:{score:100,coverage:100,maxPositions:0,openPositions:0,maxRiskPct:0,dailyLossPct:0}};
const colors:Record<string,string>={BTC:"#f4ad45",SOL:"#63eeb0",ETH:"#8996ff",BNB:"#f1d26a"};

export default function Analytics(){
 const [range,setRange]=useState<Range>("30D"),[metric,setMetric]=useState("Return"),[toast,setToast]=useState(""),[data,setData]=useState<AnalyticsData>(emptyData);
 const markets=data.markets.map(item=>({...item,color:colors[item.coin]||"#91a3ff"})),maxHour=Math.max(1,...data.hours);
 useEffect(()=>{fetch(`/api/analytics?range=${range}`,{cache:"no-store"}).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.error||"Analytics unavailable");return body}).then(setData).catch(reason=>setToast(reason instanceof Error?reason.message:"Analytics unavailable"))},[range]);
 const report=()=>{const rows=[["ChatOnYou Paper Performance",range],["Available balance",data.balance],["Allocated to open positions",data.allocated],["Period P&L",data.profit],["Period return",data.return],["Closed trades",String(data.trades)],["Wins",String(data.wins)],["Losses",String(data.losses)],["Win rate",data.win],["Maximum drawdown",data.drawdown],["Saved AI decisions",String(data.decisions)],["No-trade decisions",String(data.noTrades)],[],["Market","Trades","Win rate","P&L"],...data.markets.map(item=>[`${item.coin}/USDT`,String(item.trades),`${item.win}%`,item.pnl])],url=URL.createObjectURL(new Blob([rows.map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(",")).join("\n")],{type:"text/csv"})),link=document.createElement("a");link.href=url;link.download=`chatonyou-paper-analytics-${range.toLowerCase()}.csv`;link.click();URL.revokeObjectURL(url);setToast("Saved analytics report downloaded");setTimeout(()=>setToast(""),2300)};
 const chartLabel=useMemo(()=>metric==="Return"?data.return:metric==="P&L"?data.profit:data.win,[metric,data]);
 return <main className="analytics-shell">
  <header className="ai-dash-top"><a className="terminal-logo" href="/"><img src="/chatonyou-logo.png" alt="ChatOnYou"/><b>TRADE</b></a><div className="ai-dash-title"><b>Analytics</b><span><i/> Paper performance</span></div><div className="ai-dash-actions"><button><small>AVAILABLE PAPER CASH</small><b>{data.balance}</b></button><a href="/trade/profile">NS</a></div></header>
  <div className="ai-dash-layout"><aside className="ai-dash-nav"><div><a href="/trade"><i>↗</i><span>Trade</span></a><a href="/trade/ai"><i>✦</i><span>AI Trader</span></a><a href="/trade/bots"><i>◉</i><span>Bots</span></a><a href="/trade/wallet"><i>W</i><span>Wallet</span></a><a href="/trade/portfolio"><i>◒</i><span>Portfolio</span></a><a href="/trade/history"><i>H</i><span>History</span></a><a className="active" href="/trade/analytics"><i>⌁</i><span>Analytics</span></a><a href="/trade/backtest"><i>◫</i><span>Backtest</span></a></div><a href="/trade/settings"><i>⚙</i><span>Settings</span></a></aside>
   <section className="analytics-main">
    <div className="analytics-head"><div><span>AI PAPER PERFORMANCE</span><h1>Know what is working.</h1><p>Returns, risk and every simulated decision—clearly measured.</p></div><div className="analytics-actions"><div>{(["7D","30D","ALL"] as Range[]).map(item=><button className={range===item?"active":""} onClick={()=>setRange(item)} key={item}>{item}</button>)}</div><button onClick={report}>⇩ Export report</button></div></div>
    <div className="analytics-metrics"><article className="analytics-account"><span>AVAILABLE PAPER CASH</span><strong>{data.balance}</strong><small>{data.allocated} allocated to {data.open} open position{data.open===1?"":"s"}</small><div><b>{data.profit}</b><em>{data.return}</em></div></article><article><span>CLOSED TRADES</span><strong>{data.trades}</strong><small>{data.wins} wins · {data.losses} losses</small></article><article><span>WIN RATE</span><strong>{data.win}</strong><small>Saved paper executions only</small></article><article><span>MAX DRAWDOWN</span><strong>{data.drawdown}</strong><small>Daily limit: {data.risk.dailyLossPct}%</small><i className="risk-ok">Measured</i></article></div>
    <div className="analytics-grid">
     <article className="analytics-chart-card"><header><div><span>REALIZED P&amp;L CURVE</span><strong>{chartLabel}</strong></div><div>{["Return","P&L","Win rate"].map(item=><button className={metric===item?"active":""} onClick={()=>setMetric(item)} key={item}>{item}</button>)}</div></header><div className="analytics-chart"><div className="chart-grid-lines"><i/><i/><i/><i/></div><svg viewBox="0 0 660 150" preserveAspectRatio="none" aria-label={range+" "+metric+" chart"}><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#53e99e" stopOpacity=".28"/><stop offset="1" stopColor="#53e99e" stopOpacity="0"/></linearGradient></defs><polygon points={data.points+" 660,150 0,150"} fill="url(#area)"/><polyline points={data.points} fill="none" stroke="#55eba2" strokeWidth="3" vectorEffect="non-scaling-stroke"/></svg><b className="chart-tag">{data.profit}</b></div><footer>{data.labels.map(item=><span key={item}>{item}</span>)}</footer></article>
     <article className="risk-score-card"><header><span>RISK HEALTH</span><i>Saved rules</i></header><div className="risk-ring"><div><strong>{data.risk.score}</strong><small>/ 100</small></div></div><h2>{data.risk.coverage===100?"Protection attached":"Protection needs attention"}</h2><p>Risk health is calculated from saved positions, protection coverage and measured drawdown.</p><div className="risk-checks"><span><i>✓</i>SL / TP coverage<b>{data.risk.coverage}%</b></span><span><i>✓</i>Max risk / trade<b>{data.risk.maxRiskPct}%</b></span><span><i>✓</i>Open positions<b>{data.risk.openPositions} / {data.risk.maxPositions}</b></span></div><a href="/trade/settings">Edit risk rules →</a></article>
    </div>
    <div className="analytics-lower-grid">
     <article className="market-performance"><header><div><h2>Performance by market</h2><p>Saved closed paper trades in this period.</p></div><span>NET P&amp;L</span></header><div className="market-list">{markets.map(item=><div key={item.coin}><span className="market-symbol" style={{background:item.color}}>{item.coin[0]}</span><strong>{item.coin}/USDT<small>{item.trades} trades</small></strong><div className="market-bar"><i style={{width:item.win+"%",background:item.color}}/></div><span>{item.win}% win</span><b>{item.pnl}</b></div>)}{!markets.length&&<div className="positions-empty">No closed paper trades in this period.</div>}</div></article>
     <article className="decision-quality"><header><h2>Decision quality</h2><span>{range}</span></header><div className="quality-number"><strong>{data.noTrades}</strong><span>NO TRADE decisions<small>{data.decisions} quant decisions saved</small></span></div><div className="quality-bars"><span><i style={{width:data.highConfidencePct+"%"}}/><b>High-confidence signals</b><em>{data.highConfidencePct}%</em></span><span><i style={{width:data.targetReachedPct+"%"}}/><b>Take-profit exits</b><em>{data.targetReachedPct}%</em></span><span><i style={{width:"100%"}}/><b>Server risk checks</b><em>100%</em></span></div><p>Skipping a weak setup is counted as a valid AI decision—not a missed trade.</p></article>
     <article className="active-hours"><header><h2>AI activity</h2><span>LOCAL TIME</span></header><p>Saved quant decisions by time of day</p><div className="hour-bars">{data.hours.map((count,index)=><i title={`${count} decisions`} style={{height:Math.max(4,count/maxHour*100)+"%"}} key={index}/>)}</div><footer><span>00:00</span><span>12:00</span><span>23:00</span></footer><div className="best-window"><i>✦</i><span><b>{data.decisions} saved decisions</b><small>Based only on authenticated account activity</small></span></div></article>
    </div>
    <p className="ai-data-note">Analytics use your saved paper trades and quant decisions · Not investment advice · Simulated results do not guarantee future performance</p>
   </section>
  </div>
  {toast&&<div className="toast"><span>✓</span>{toast}</div>}
  <nav className="ai-mobile-nav"><a href="/trade"><i>↗</i>Trade</a><a href="/trade/ai"><i>✦</i>AI</a><a href="/trade/bots"><i>◉</i>Bots</a><a href="/trade/history"><i>H</i>History</a><a className="active" href="/trade/analytics"><i>⌁</i>Stats</a></nav>
 </main>
}
