"use client";
import { useMemo,useState } from "react";

type Market={coin:string,name:string,symbol:string,color:string,price:string,change:string,signal:string,confidence:number,trend:string,volatility:string,volume:string,reason:string,entry:string,stop:string,target:string,fav:boolean};
const initial:Market[]=[
 {coin:"SOL",name:"Solana",symbol:"S",color:"#92ffc7",price:"$182.44",change:"+4.21%",signal:"BUY",confidence:84,trend:"Bullish",volatility:"Normal",volume:"+38%",reason:"Resistance breakout confirmed with strong volume and bullish EMA alignment.",entry:"$182.44",stop:"$178.80",target:"$189.20",fav:true},
 {coin:"ETH",name:"Ethereum",symbol:"◆",color:"#8293ff",price:"$4,216.12",change:"+1.36%",signal:"BUY",confidence:81,trend:"Bullish",volatility:"Low",volume:"+21%",reason:"Momentum recovered above support while sell pressure continued to weaken.",entry:"$4,216",stop:"$4,168",target:"$4,308",fav:true},
 {coin:"BTC",name:"Bitcoin",symbol:"₿",color:"#f5a623",price:"$113,240.80",change:"+2.84%",signal:"NO TRADE",confidence:64,trend:"Bullish",volatility:"Normal",volume:"+12%",reason:"Trend remains constructive but resistance confirmation is still missing.",entry:"Waiting",stop:"—",target:"—",fav:true},
 {coin:"BNB",name:"BNB",symbol:"B",color:"#f1d26a",price:"$846.20",change:"+0.92%",signal:"NO TRADE",confidence:58,trend:"Sideways",volatility:"High",volume:"-8%",reason:"Abnormal volatility filter is active and order-book direction is unclear.",entry:"Waiting",stop:"—",target:"—",fav:false},
 {coin:"XRP",name:"XRP",symbol:"X",color:"#e9eef0",price:"$3.14",change:"-1.18%",signal:"SELL",confidence:79,trend:"Bearish",volatility:"Normal",volume:"+17%",reason:"Price lost support with increasing sell volume and negative momentum.",entry:"$3.14",stop:"$3.19",target:"$3.02",fav:false},
 {coin:"ADA",name:"Cardano",symbol:"A",color:"#6f9cff",price:"$0.98",change:"+0.42%",signal:"NO TRADE",confidence:61,trend:"Sideways",volatility:"Low",volume:"-3%",reason:"No directional edge. AI is waiting for volume and trend confirmation.",entry:"Waiting",stop:"—",target:"—",fav:false},
 {coin:"AVAX",name:"Avalanche",symbol:"A",color:"#ff6f78",price:"$31.62",change:"+3.08%",signal:"BUY",confidence:77,trend:"Bullish",volatility:"High",volume:"+31%",reason:"Momentum is positive, but higher volatility reduces confidence below auto threshold.",entry:"$31.62",stop:"$30.71",target:"$33.28",fav:false},
 {coin:"LINK",name:"Chainlink",symbol:"L",color:"#7893ff",price:"$25.84",change:"-0.64%",signal:"SELL",confidence:73,trend:"Bearish",volatility:"Normal",volume:"+9%",reason:"Lower highs and weakening volume suggest continued downside pressure.",entry:"$25.84",stop:"$26.32",target:"$24.90",fav:false},
];

// The quant signal engine only covers these markets. Everything else in the
// scanner is market context and cannot be sent to the paper order screen.
const tradable=new Set(["BTC","ETH","SOL","BNB"]);

export default function Markets(){
 const [markets,setMarkets]=useState(initial),[filter,setFilter]=useState("All"),[query,setQuery]=useState(""),[sort,setSort]=useState("Confidence"),[selected,setSelected]=useState<Market|null>(null),[preparing,setPreparing]=useState(false),[prepareError,setPrepareError]=useState(""),toast="";
 const visible=useMemo(()=>markets.filter(item=>(filter==="All"||filter==="Watchlist"&&item.fav||item.signal===filter)&&item.coin.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==="Confidence"?b.confidence-a.confidence:sort==="24H change"?parseFloat(b.change)-parseFloat(a.change):a.coin.localeCompare(b.coin)),[markets,filter,query,sort]);
 const fav=(coin:string)=>setMarkets(items=>items.map(item=>item.coin===coin?{...item,fav:!item.fav}:item));
 const execute=async(item:Market)=>{if(item.signal==="NO TRADE"||!tradable.has(item.coin)||preparing)return;setPreparing(true);setPrepareError("");try{const response=await fetch(`/api/signals?asset=${item.coin}`,{cache:"no-store"}),signal=await response.json();if(!response.ok)throw new Error(signal.error||"Live signal unavailable");if(signal.signal!==item.signal||signal.confidence<80)throw new Error(`Live engine now says ${signal.signal} at ${signal.confidence}% confidence.`);window.location.href=`/trade/order?asset=${item.coin}&side=${signal.signal}&amount=500`}catch(reason){setPrepareError(reason instanceof Error?reason.message:"Live signal unavailable. Try again later.");setPreparing(false)}};
 return <main className="markets-shell">
  <header className="ai-dash-top"><a className="terminal-logo" href="/"><img src="/chatonyou-logo.png" alt="ChatOnYou"/><b>TRADE</b></a><div className="ai-dash-title"><b>Market Scanner</b><span><i/> {markets.length} markets ranked</span></div><div className="ai-dash-actions"><button><small>DEMO SNAPSHOT</small><b>Paper only</b></button><a href="/trade/profile">NS</a></div></header>
  <div className="ai-dash-layout"><aside className="ai-dash-nav"><div><a href="/trade"><i>↗</i><span>Trade</span></a><a className="active" href="/trade/markets"><i>⌕</i><span>Markets</span></a><a href="/trade/ai"><i>✦</i><span>AI Trader</span></a><a href="/trade/bots"><i>◉</i><span>Bots</span></a><a href="/trade/wallet"><i>W</i><span>Wallet</span></a><a href="/trade/portfolio"><i>◒</i><span>Portfolio</span></a><a href="/trade/history"><i>H</i><span>History</span></a><a href="/trade/analytics"><i>⌁</i><span>Analytics</span></a></div><a href="/trade/settings"><i>⚙</i><span>Settings</span></a></aside>
   <section className="markets-main">
    <div className="markets-head"><div><span>AI OPPORTUNITY SCANNER</span><h1>See what AI sees.</h1><p>Selected markets ranked by signal strength, trend and risk.</p></div><div className="market-scan-status"><i><b/></i><span><b>Scanner snapshot ready</b><small>Orders re-check live data</small></span></div></div>
    <section className="market-leaders"><article className="leader-buy" onClick={()=>setSelected(markets[0])}><header><span>TOP OPPORTUNITY</span><i>BUY</i></header><div><span className="leader-symbol" style={{background:markets[0].color}}>S</span><strong>SOL/USDT<small>$182.44 · +4.21%</small></strong><b>84<small>% confidence</small></b></div><p>Volume breakout with bullish trend confirmation.</p><footer><span>Risk / reward<b>1 : 2.1</b></span><span>Volatility<b>Normal</b></span><em>View signal →</em></footer></article><article><header><span>MARKET MOOD</span><i>Mixed</i></header><div className="market-mood"><span><b>3</b><small>BUY</small></span><span><b>2</b><small>SELL</small></span><span><b>19</b><small>NO TRADE</small></span></div><p>AI remains selective. Most markets do not meet the 80% confidence rule.</p></article><article><header><span>RISK ENVIRONMENT</span><i className="market-safe">Protected</i></header><div className="risk-weather"><i>◇</i><span><b>Normal conditions</b><small>2 high-volatility markets filtered</small></span></div><div className="risk-weather-bars"><i/><i/><i/><i/><i/></div><footer>Daily risk usage <b>0.8% / 3%</b></footer></article></section>
    <section className="scanner-card">
     <header><div className="scanner-filters">{["All","Watchlist","BUY","SELL","NO TRADE"].map(item=><button className={filter===item?"active":""} onClick={()=>setFilter(item)} key={item}>{item}{item==="Watchlist"&&<i>{markets.filter(m=>m.fav).length}</i>}</button>)}</div><div className="scanner-tools"><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search market"/></label><select value={sort} onChange={e=>setSort(e.target.value)}><option>Confidence</option><option>24H change</option><option>Market A–Z</option></select></div></header>
     <div className="scanner-table"><div className="scanner-labels"><span>MARKET</span><span>PRICE</span><span>24H</span><span>AI SIGNAL</span><span>CONFIDENCE</span><span>TREND</span><span>VOLATILITY</span><span>VOLUME</span><span/></div>{visible.map(item=><button className="scanner-row" onClick={()=>setSelected(item)} key={item.coin}><span className="scanner-market"><i onClick={e=>{e.stopPropagation();fav(item.coin)}} className={item.fav?"fav":""}>★</i><em style={{background:item.color}}>{item.symbol}</em><b>{item.coin}/USDT<small>{item.name}</small></b></span><strong>{item.price}</strong><em className={item.change.startsWith("+")?"market-up":"market-down"}>{item.change}</em><span className={"scanner-signal "+item.signal.toLowerCase().replace(" ","-")}>{item.signal}</span><span className="confidence-cell"><b>{item.confidence}%</b><i><em style={{width:item.confidence+"%"}}/></i></span><span className={item.trend==="Bullish"?"trend-up":item.trend==="Bearish"?"trend-down":""}>{item.trend}</span><span>{item.volatility}</span><span className={item.volume.startsWith("+")?"market-up":"market-down"}>{item.volume}</span><i>›</i></button>)}{!visible.length&&<div className="scanner-empty"><i>⌕</i><h3>No markets found</h3><p>Try another filter or coin symbol.</p></div>}</div>
    </section>
    <section className="scanner-explain"><div><span>✦</span><p><b>How ranking works</b><small>Confidence combines trend, momentum, volume, volatility and risk checks. NO TRADE is a valid protective decision.</small></p></div><a href="/trade/settings">Edit confidence rule →</a></section>
    <p className="ai-data-note">Curated scanner snapshot · Confirmed paper orders re-check live Binance public candles and server risk rules · Not investment advice</p>
   </section>
  </div>
  {selected&&<div className="scanner-drawer-bg" onClick={()=>setSelected(null)}><aside className="scanner-drawer" onClick={e=>e.stopPropagation()}><header><div className="drawer-market-name"><i style={{background:selected.color}}>{selected.symbol}</i><span><b>{selected.coin}/USDT</b><small>{selected.name} · Spot</small></span></div><button onClick={()=>setSelected(null)}>×</button></header><section className="drawer-market-price"><span>CURRENT DEMO PRICE</span><strong>{selected.price}</strong><b className={selected.change.startsWith("+")?"market-up":"market-down"}>{selected.change} today</b><div><i/><i/><i/><i/><i/><i/><i/><i/></div></section><div className={"drawer-signal "+selected.signal.toLowerCase().replace(" ","-")}><span>AI SIGNAL · SNAPSHOT</span><strong>{selected.signal}</strong><div><b>{selected.confidence}%</b><small>confidence</small></div><i><em style={{width:selected.confidence+"%"}}/></i></div><section className="drawer-ai-reason"><span>✦ WHY THIS DECISION</span><p>{selected.reason}</p><ul><li><i>✓</i>Trend: <b>{selected.trend}</b></li><li><i>✓</i>Volume: <b>{selected.volume}</b></li><li><i>◇</i>Volatility: <b>{selected.volatility}</b></li></ul></section><div className="drawer-trade-levels"><span>Entry<b>{selected.entry}</b></span><span>Stop loss<b>{selected.stop}</b></span><span>Take profit<b>{selected.target}</b></span><span>Risk<b>{selected.signal==="NO TRADE"?"0%":"0.8%"}</b></span></div>{prepareError?<div className="no-trade-message"><i>!</i><span><b>Live verification blocked this order</b><small>{prepareError}</small></span></div>:null}{selected.signal==="NO TRADE"?<div className="no-trade-message"><i>◇</i><span><b>Capital stays protected</b><small>AI will wait until confidence reaches your 80% rule.</small></span></div>:!tradable.has(selected.coin)?<div className="no-trade-message"><i>◇</i><span><b>Not available for paper trading</b><small>The quant engine covers BTC, ETH, SOL and BNB only. {selected.coin} is shown for market context.</small></span></div>:<button className={"prepare-trade "+selected.signal.toLowerCase()} disabled={preparing} onClick={()=>void execute(selected)}>{preparing?"Verifying live signal…":`Verify & prepare ${selected.signal} paper trade`} <span>→</span></button>}<a className="open-chart-link" href="/trade">Open {selected.coin} chart <span>↗</span></a></aside></div>}
  {toast&&<div className="toast"><span>✓</span>{toast}</div>}
  <nav className="ai-mobile-nav"><a href="/trade"><i>↗</i>Trade</a><a className="active" href="/trade/markets"><i>⌕</i>Markets</a><a href="/trade/ai"><i>✦</i>AI</a><a href="/trade/bots"><i>◉</i>Bots</a><a href="/trade/profile"><i>◎</i>Profile</a></nav>
 </main>
}
