"use client";
import { useEffect,useState } from "react";
export default function EmergencyStop(){
 const [checked,setChecked]=useState(false),[stopped,setStopped]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{fetch("/api/safety",{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then(data=>setStopped(Boolean(data.emergencyStop))).catch(()=>{})},[]);
 const stop=async()=>{setBusy(true);setError("");try{const response=await fetch("/api/safety",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"stop"})}),data=await response.json();if(!response.ok)throw new Error(data.error||"Emergency stop failed");setStopped(true)}catch(reason){setError(reason instanceof Error?reason.message:"Emergency stop failed")}finally{setBusy(false)}};
 return <main className="finish-flow-shell emergency-shell"><header className="finish-flow-top"><a className="terminal-logo" href="/"><img src="/chatonyou-logo.png" alt="ChatOnYou"/><b>TRADE</b></a><div><i>!</i><span><b>Emergency Safety</b><small>Paper + Testnet control</small></span></div><a href="/trade">×</a></header>
  {!stopped?<section className="emergency-main"><div className="emergency-orbit"><i>Ⅱ</i><span/><b/></div><span>EMERGENCY STOP</span><h1>Stop every new entry.<br/><em>Keep exits protected.</em></h1><p>This immediately blocks paper orders and Binance Testnet entries. Existing Testnet OCO stop-loss and take-profit orders remain active.</p><section className="emergency-card"><header><div><span>CURRENT AUTOMATION</span><h2>Paper + Testnet execution</h2></div><em>READY</em></header><div><article><i>×</i><span><b>New paper entries</b><small>Blocked immediately</small></span><em>Stop</em></article><article><i>Ⅱ</i><span><b>AI Auto Testnet</b><small>Scanning and new orders pause</small></span><em>Pause</em></article><article><i>✓</i><span><b>Protective Binance exits</b><small>Existing OCO orders stay active</small></span><em className="safe">Keep</em></article></div><label className={checked?"checked":""}><button onClick={()=>setChecked(!checked)}>{checked?"✓":""}</button><span><b>I understand this pauses all new entries</b><small>It does not guarantee profit or close positions at a specific price.</small></span></label>{error?<p className="order-api-error">{error}</p>:null}<footer><a href="/trade">Cancel</a><button disabled={!checked||busy} onClick={stop}>{busy?"Stopping…":"Stop all new entries"} <b>→</b></button></footer></section><small>Existing Testnet protection remains on Binance Spot Testnet</small></section>:
   <section className="finish-success emergency-success"><div><i>✓</i><span/><b/></div><span>EMERGENCY STOP ACTIVE</span><h1>Automation paused.<br/><em>Capital stays guarded.</em></h1><p>All paper and Testnet entries are blocked. Existing Binance Testnet OCO exits remain active. Manual review is required before any resume.</p><article><span>AI Auto<b>OFF</b></span><span>New entries<b>Blocked</b></span><span>Protective exits<b>Active</b></span></article><div><a href="/trade/testnet">Review Testnet positions</a><a href="/trade/settings">Open safety settings</a></div><small>Resume is available only inside the Testnet safety panel.</small></section>}
 </main>
}
