"use client";
import { useState } from "react";

export default function PaperReset(){
 const [step,setStep]=useState(1),[typed,setTyped]=useState(""),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const finishReset=async()=>{setSaving(true);setError("");try{const response=await fetch("/api/account",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"reset"})}),data=await response.json();if(!response.ok)throw new Error(data.error||"Reset could not be saved");setStep(3)}catch(reason){setError(reason instanceof Error?reason.message:"Reset failed")}finally{setSaving(false)}};
 return <main className="finish-flow-shell"><header className="finish-flow-top"><a className="terminal-logo" href="/"><img src="/chatonyou-logo.png" alt="ChatOnYou"/><b>TRADE</b></a><div><i>↻</i><span><b>Paper Account Reset</b><small>Demo data only</small></span></div><a href="/trade/settings">×</a></header>
  {step<3?<section className="finish-flow-main"><div className="finish-flow-copy"><span>NEW SIMULATION</span><h1>Start fresh.<br/><em>Learn from zero.</em></h1><p>Your virtual balance, paper positions and performance history will reset. Risk settings return to safe defaults.</p><div className="finish-steps"><span className="done"><i>✓</i>Review</span><b/><span className={step===2?"active":""}><i>2</i>Confirm</span><b/><span><i>3</i>Ready</span></div></div>
   <section className="finish-card reset-card"><header><div><span>{step===1?"RESET SUMMARY":"FINAL CONFIRMATION"}</span><h2>{step===1?"What will change":"Type RESET to continue"}</h2></div><i>PAPER ONLY</i></header>{step===1?<><div className="reset-items"><span><i>₹</i><b>Virtual balance<small>Current balance → ₹10,000</small></b><em>Reset</em></span><span><i>↗</i><b>Open paper positions<small>Saved simulated positions will be cleared</small></b><em>Clear</em></span><span><i>H</i><b>Saved trade history<small>Authenticated paper records will be removed</small></b><em>Clear</em></span><span><i>◇</i><b>Risk protection<small>Safe defaults will be restored</small></b><em className="keep">Restore</em></span></div><div className="finish-note"><i>i</i><span><b>This cannot affect real funds</b><small>No exchange is connected and no real order can be created.</small></span></div></>:<><div className="reset-confirm-copy"><i>!</i><h3>This creates a brand-new paper session.</h3><p>Your saved virtual balance, settings and paper orders will reset securely.</p><label>Confirmation phrase<input value={typed} onChange={e=>setTyped(e.target.value.toUpperCase())} placeholder="Type RESET" autoFocus/></label></div><div className="finish-note warning"><i>◇</i><span><b>No undo after confirmation</b><small>You can start another simulation whenever you want.</small></span></div></>}
    {error&&<p className="reset-api-error">{error}</p>}<footer><button onClick={()=>step===1?window.location.href="/trade/settings":setStep(1)}>Back</button><button disabled={saving||(step===2&&typed!=="RESET")} onClick={()=>step===1?setStep(2):finishReset()}>{step===1?"Continue":saving?"Saving reset…":"Reset paper account"}<b>→</b></button></footer></section></section>:
   <section className="finish-success"><div><i>✓</i><span/><b/></div><span>NEW PAPER SESSION READY</span><h1>₹10,000 virtual.<br/><em>Clean start.</em></h1><p>Saved paper positions are cleared. AI stays in Copilot mode until you choose new settings.</p><article><span>Virtual balance<b>₹10,000.00</b></span><span>Open positions<b>0</b></span><span>AI mode<b>Copilot</b></span></article><div><a href="/trade">Open trading terminal</a><a href="/trade/settings">Review risk settings</a></div><small>Persistent paper reset saved to your authenticated account</small></section>}
 </main>
}
