"use client";
import { useEffect,useState } from "react";

const initialNotifications=[
 {id:1,icon:"✦",tone:"ai",title:"High-confidence SOL opportunity",text:"AI confidence reached 84%. Paper position prepared.",time:"12 min ago",unread:true},
 {id:2,icon:"✓",tone:"safe",title:"Take-profit completed",text:"BTC/USDT paper position closed at $113,240.",time:"1 hour ago",unread:true},
 {id:3,icon:"◇",tone:"risk",title:"Risk engine paused an entry",text:"BNB volatility exceeded your configured safety limit.",time:"3 hours ago",unread:false},
 {id:4,icon:"⌁",tone:"report",title:"Weekly paper report is ready",text:"34 trades · 61.7% win rate · -2.8% maximum drawdown.",time:"Yesterday",unread:false},
];
const sessions=[
 {id:"current",device:"Chrome on macOS",place:"Jaipur, India",time:"Active now",icon:"▰",current:true},
 {id:"mobile",device:"ChatOnYou Mobile",place:"Jaipur, India",time:"2 hours ago",icon:"▯",current:false},
];

export default function Profile(){
 const [tab,setTab]=useState("Overview"),[name,setName]=useState("Paper trader"),[email,setEmail]=useState(""),[edit,setEdit]=useState(false),[signout,setSignout]=useState(false),[notifications,setNotifications]=useState(initialNotifications),[activeSessions,setActiveSessions]=useState(sessions),[toast,setToast]=useState(""),[filter,setFilter]=useState("All"),[balance,setBalance]=useState(10000),[startingBalance,setStartingBalance]=useState(10000),[tradeCount,setTradeCount]=useState(0);
 const unread=notifications.filter(item=>item.unread).length;
 const filteredNotifications=notifications.filter(item=>filter==="All"||filter==="AI activity"&&item.tone==="ai"||filter==="Trading"&&item.tone==="safe"||filter==="Risk"&&item.tone==="risk");
 const markAll=()=>setNotifications(items=>items.map(item=>({...item,unread:false})));
 const flash=(message:string)=>{setToast(message);setTimeout(()=>setToast(""),2300)};
 useEffect(()=>{fetch("/api/account",{cache:"no-store"}).then(response=>response.json()).then(data=>{if(data.user){setName(data.user.displayName);setEmail(data.user.email)}if(data.account){setBalance(data.account.balance);setStartingBalance(data.account.startingBalance)}setTradeCount((data.trades||[]).length)}).catch(()=>flash("Profile sync is temporarily unavailable"))},[]);
 return <main className="profile-shell">
  <header className="ai-dash-top"><a className="terminal-logo" href="/"><img src="/chatonyou-logo.png" alt="ChatOnYou"/><b>TRADE</b></a><div className="ai-dash-title"><b>Profile</b><span><i/> Paper account</span></div><div className="ai-dash-actions"><button><small>SAVED PAPER BALANCE</small><b>₹{balance.toLocaleString("en-IN",{minimumFractionDigits:2})}</b></button><a className="active-profile" href="/trade/profile">{name.slice(0,2).toUpperCase()}</a></div></header>
  <div className="ai-dash-layout"><aside className="ai-dash-nav"><div><a href="/trade"><i>↗</i><span>Trade</span></a><a href="/trade/ai"><i>✦</i><span>AI Trader</span></a><a href="/trade/bots"><i>◉</i><span>Bots</span></a><a href="/trade/wallet"><i>W</i><span>Wallet</span></a><a href="/trade/portfolio"><i>◒</i><span>Portfolio</span></a><a href="/trade/history"><i>H</i><span>History</span></a><a href="/trade/analytics"><i>⌁</i><span>Analytics</span></a><a href="/trade/backtest"><i>◫</i><span>Backtest</span></a></div><a href="/trade/settings"><i>⚙</i><span>Settings</span></a></aside>
   <section className="profile-main">
    <div className="profile-head"><div><span>ACCOUNT CENTER</span><h1>Your profile</h1><p>Paper account, alerts and active sessions in one place.</p></div><button onClick={()=>setEdit(true)}>Edit profile</button></div>
    <section className="profile-identity"><div className="profile-avatar">NS<i/></div><div><span>PAPER MEMBER</span><h2>{name}</h2><p>{email} · India</p></div><div className="profile-identity-stats"><span>Member since<b>Aug 2026</b></span><span>Account type<b>Paper Trading</b></span><span>Risk status<b className="profile-positive">Protected</b></span></div></section>
    <div className="profile-tabs">{["Overview","Notifications","Security"].map(item=><button className={tab===item?"active":""} onClick={()=>setTab(item)} key={item}>{item}{item==="Notifications"&&unread>0&&<i>{unread}</i>}</button>)}</div>
    {tab==="Overview"&&<div className="profile-overview">
     <section className="profile-account-card"><header><span>AI PAPER ACCOUNT</span><a href="/trade/analytics">View analytics →</a></header><strong>₹{balance.toLocaleString("en-IN",{minimumFractionDigits:2})}</strong><small>Started with ₹{startingBalance.toLocaleString("en-IN")} virtual</small><div className="profile-account-gain"><b>{balance-startingBalance>=0?"+":"-"}₹{Math.abs(balance-startingBalance).toLocaleString("en-IN")}</b><span>saved paper balance</span></div><div className="profile-account-line"><i/><b>Paper</b></div><footer><span>Total trades<b>{tradeCount}</b></span><span>Execution<b>Saved</b></span><span>Risk mode<b>Protected</b></span></footer></section>
     <section className="profile-ai-card"><header><span>AI STATUS</span><i>Watching</i></header><div className="profile-ai-orbit"><i>✦</i><b/><b/></div><h3>24 markets monitored</h3><p>Last decision: <b>NO TRADE</b></p><small>BTC confidence only 64%—waiting for confirmation.</small><a href="/trade/ai">Open AI dashboard →</a></section>
     <section className="profile-quick"><header><h2>Quick access</h2></header><div><a href="/trade/guide"><i>?</i><span><b>AI Guide</b><small>Simple Hindi-friendly help</small></span><em>›</em></a><a href="/trade/history"><i>H</i><span><b>Trade history</b><small>Orders &amp; AI audit</small></span><em>›</em></a><a href="/trade/settings"><i>⚙</i><span><b>Risk settings</b><small>Limits &amp; protection</small></span><em>›</em></a><a href="/trade/localization"><i>文</i><span><b>Language &amp; region</b><small>Hindi-friendly · INR</small></span><em>›</em></a></div></section>
     <section className="profile-recent"><header><div><h2>Recent notifications</h2><p>Your latest account and AI activity.</p></div><button onClick={()=>setTab("Notifications")}>View all</button></header><div>{notifications.slice(0,3).map(item=><article key={item.id}><i className={item.tone}>{item.icon}</i><span><b>{item.title}</b><small>{item.text}</small></span><em>{item.time}</em>{item.unread&&<strong/>}</article>)}</div></section>
    </div>}
    {tab==="Notifications"&&<section className="notification-center"><header><div><h2>Notifications</h2><p>AI decisions, trades and risk alerts.</p></div><button onClick={markAll} disabled={!unread}>✓ Mark all as read</button></header><div className="notification-filters">{["All","AI activity","Trading","Risk"].map(item=><button key={item} className={filter===item?"active":""} onClick={()=>setFilter(item)}>{item}{item==="All"&&<i>{notifications.length}</i>}</button>)}</div><div className="notification-list">{filteredNotifications.map(item=><button className={item.unread?"unread":""} onClick={()=>{setNotifications(items=>items.map(note=>note.id===item.id?{...note,unread:false}:note));if(item.id===3) window.location.href="/trade/volatility-pause"}} key={item.id}><i className={item.tone}>{item.icon}</i><span><b>{item.title}</b><small>{item.text}</small></span><em>{item.time}</em>{item.unread&&<strong/>}</button>)}</div>{!filteredNotifications.length&&<div className="notification-empty"><i>✓</i><span><b>No {filter.toLowerCase()} alerts</b><small>New matching paper-account activity will appear here.</small></span></div>}</section>}
    {tab==="Security"&&<section className="profile-security">
     <article><header><div><h2>Account security</h2><p>Protection for future real-account connections.</p></div><i>Demo</i></header><div className="security-score"><div><strong>72</strong><small>/ 100</small></div><span><b>Good protection</b><small>Add two-step verification before connecting an exchange.</small></span></div><div className="security-items"><span><i>✓</i><b>Email address<small>{email}</small></b><em>Verified</em></span><span><i>!</i><b>Two-step verification<small>Required for real trading</small></b><button onClick={()=>flash("Two-step setup will activate with authentication APIs")}>Set up later</button></span><span><i>◇</i><b>Withdrawal permission<small>Blocked by product design</small></b><em>Disabled</em></span></div></article>
     <article><header><div><h2>Active sessions</h2><p>Devices currently signed into this demo account.</p></div><span>{activeSessions.length} sessions</span></header><div className="session-list">{activeSessions.map(item=><div key={item.id}><i>{item.icon}</i><span><b>{item.device}{item.current&&<em>Current</em>}</b><small>{item.place} · {item.time}</small></span>{item.current?<strong>Active</strong>:<button onClick={()=>{setActiveSessions(list=>list.filter(session=>session.id!==item.id));flash("Demo mobile session removed")}}>Sign out</button>}</div>)}</div></article>
     <article className="profile-signout-card"><span><b>Sign out of ChatOnYou Trade</b><small>Your paper demo data will remain available.</small></span><button onClick={()=>setSignout(true)}>Sign out</button></article>
    </section>}
    <p className="ai-data-note">Identity and paper balance are loaded from your authenticated account · Notification and session examples are illustrative</p>
   </section>
  </div>
  {edit&&<div className="profile-modal-bg"><section className="edit-profile-modal"><header><div><span>PROFILE DETAILS</span><h2>Edit profile</h2></div><button onClick={()=>setEdit(false)}>×</button></header><div className="edit-avatar">{name.slice(0,2).toUpperCase()}<button onClick={()=>flash("Photo upload is not available in paper mode")}>Change photo</button></div><label>Full name<div><input value={name} onChange={e=>setName(e.target.value)}/></div></label><label>Email address<div><input type="email" value={email} readOnly/><i>Verified</i></div></label><label>Country<div><select defaultValue="India"><option>India</option><option>United States</option><option>United Arab Emirates</option></select></div></label><button className="profile-save" onClick={()=>{setEdit(false);flash("Display preview updated on this device")}}>Save profile <span>→</span></button></section></div>}
  {signout&&<div className="profile-modal-bg"><section className="signout-modal"><i>↗</i><h2>Sign out?</h2><p>This ends the current session. Your saved paper portfolio remains unchanged.</p><div><button onClick={()=>setSignout(false)}>Cancel</button><a href="/signout-with-chatgpt?return_to=%2Flogin">Sign out</a></div></section></div>}
  {toast&&<div className="toast"><span>✓</span>{toast}</div>}
  <nav className="ai-mobile-nav"><a href="/trade"><i>↗</i>Trade</a><a href="/trade/ai"><i>✦</i>AI</a><a href="/trade/bots"><i>◉</i>Bots</a><a href="/trade/wallet"><i>W</i>Wallet</a><a className="active" href="/trade/profile"><i>◎</i>Profile</a></nav>
 </main>
}
