"use client";
import { useEffect, useState } from "react";

type ExchangeConnection={apiKeyHint:string;canTrade:boolean;status:string;lastCheckedAt:number;balances:Array<{asset:string;free:string;locked:string}>};

const holdings=[
 {coin:"USDT",name:"Tether",symbol:"₮",color:"#58d6a0",amount:"8,716.40",value:"₹7,28,449",share:67},
 {coin:"BTC",name:"Bitcoin",symbol:"₿",color:"#f5a623",amount:"0.0142",value:"₹1,34,680",share:19},
 {coin:"ETH",name:"Ethereum",symbol:"◆",color:"#8293ff",amount:"0.184",value:"₹64,720",share:9},
 {coin:"SOL",name:"Solana",symbol:"S",color:"#92ffc7",amount:"1.68",value:"₹25,132",share:5},
];
const transactions=[
 {time:"Today · 11:18",type:"Paper BUY",coin:"SOL",amount:"+2.80 SOL",value:"₹42,000",status:"Completed"},
 {time:"Today · 09:54",type:"Paper SELL",coin:"ETH",amount:"-0.12 ETH",value:"₹42,160",status:"Completed"},
 {time:"Yesterday",type:"P&amp;L Credit",coin:"USDT",amount:"+1.42 USDT",value:"+₹118.40",status:"Settled"},
 {time:"18 Aug",type:"Paper BUY",coin:"BTC",amount:"+0.004 BTC",value:"₹37,820",status:"Completed"},
 {time:"16 Aug",type:"Virtual Deposit",coin:"USDT",amount:"+100 USDT",value:"₹8,358",status:"Settled"},
];

export default function Wallet(){
 const [connect,setConnect]=useState(false),[funds,setFunds]=useState(false),[connection,setConnection]=useState<ExchangeConnection|null>(null),[amount,setAmount]=useState(10000),[balance,setBalance]=useState(10000),[showKey,setShowKey]=useState(false),[apiKey,setApiKey]=useState(""),[secret,setSecret]=useState(""),[exchangeBusy,setExchangeBusy]=useState(false),[exchangeError,setExchangeError]=useState(""),[fundsBusy,setFundsBusy]=useState(false),[fundsError,setFundsError]=useState(""),[hideSmall,setHideSmall]=useState(false),[showAll,setShowAll]=useState(false);
 const connected=Boolean(connection);
 const visibleHoldings=hideSmall?holdings.filter(item=>item.share>=10):holdings;
 useEffect(()=>{Promise.all([fetch("/api/account",{cache:"no-store"}),fetch("/api/exchange",{cache:"no-store"})]).then(async([accountResponse,exchangeResponse])=>{if(accountResponse.ok){const data=await accountResponse.json();setBalance(data.account.balance)}if(exchangeResponse.ok){const data=await exchangeResponse.json();setConnection(data.connection)}}).catch(()=>undefined)},[]);
 const addFunds=async()=>{setFundsBusy(true);setFundsError("");try{const response=await fetch("/api/account",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"add_funds",amount})}),data=await response.json();if(!response.ok)throw new Error(data.error||"Could not add virtual funds");setBalance(data.balance);setFunds(false)}catch(reason){setFundsError(reason instanceof Error?reason.message:"Could not add virtual funds")}finally{setFundsBusy(false)}};
 const connectExchange=async()=>{if(!apiKey||!secret)return;setExchangeBusy(true);setExchangeError("");try{const response=await fetch("/api/exchange",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({apiKey,apiSecret:secret})}),data=await response.json();if(!response.ok)throw new Error(data.error||"Connection failed");setConnection(data.connection);setConnect(false);setApiKey("");setSecret("")}catch(reason){setExchangeError(reason instanceof Error?reason.message:"Connection failed")}finally{setExchangeBusy(false)}};
 const refreshExchange=async()=>{setExchangeBusy(true);setExchangeError("");try{const response=await fetch("/api/exchange",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"refresh"})}),data=await response.json();if(!response.ok)throw new Error(data.error||"Refresh failed");setConnection(data.connection)}catch(reason){setExchangeError(reason instanceof Error?reason.message:"Refresh failed")}finally{setExchangeBusy(false)}};
 const disconnectExchange=async()=>{setExchangeBusy(true);setExchangeError("");try{const response=await fetch("/api/exchange",{method:"DELETE"});if(!response.ok)throw new Error("Disconnect failed");setConnection(null)}catch(reason){setExchangeError(reason instanceof Error?reason.message:"Disconnect failed")}finally{setExchangeBusy(false)}};
 return <main className="wallet-shell"><header className="ai-dash-top"><a className="terminal-logo" href="/"><img src="/chatonyou-logo.png" alt="ChatOnYou"/><b>TRADE</b></a><div className="ai-dash-title"><b>Wallet</b><span><i/> Paper account</span></div><div className="ai-dash-actions"><button><small>DEMO BALANCE</small><b>₹{balance.toLocaleString("en-IN")}.00</b></button><a href="/trade/profile">NS</a></div></header><div className="ai-dash-layout"><aside className="ai-dash-nav"><div><a href="/trade"><i>↗</i><span>Trade</span></a><a href="/trade/ai"><i>✦</i><span>AI Trader</span></a><a href="/trade/bots"><i>◉</i><span>Bots</span></a><a className="active" href="/trade/wallet"><i>▰</i><span>Wallet</span></a><a href="/trade/portfolio"><i>◒</i><span>Portfolio</span></a><a href="/trade/history"><i>H</i><span>History</span></a><a href="/trade/analytics"><i>⌁</i><span>Analytics</span></a><a href="/trade/backtest"><i>◫</i><span>Backtest</span></a></div><a href="/trade/settings"><i>⚙</i><span>Settings</span></a></aside><section className="wallet-main">
  <div className="wallet-head"><div><span>PAPER WALLET</span><h1>Funds &amp; connections</h1><p>Manage virtual capital now. Exchange access stays separate and permission-controlled.</p></div><div><button onClick={()=>setFunds(true)}>+ Add virtual funds</button>{connection?.canTrade?<button onClick={()=>window.location.href="/trade/testnet"}>Open Testnet <i>↗</i></button>:<button onClick={()=>setConnect(true)}>Connect exchange <i>↗</i></button>}</div></div>
  <section className="wallet-hero"><div className="wallet-balance-card"><header><span>TOTAL PAPER BALANCE</span><i>DEMO</i></header><strong>₹{balance.toLocaleString("en-IN")}.00</strong><p>≈ $130.10 virtual USDT value</p><div className="wallet-change"><b>+₹842.00</b><span>+8.42% all time</span></div><div className="balance-spark"><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/></div><footer><span>Available<b>₹9,716</b></span><span>In positions<b>₹1,126</b></span><span>Reserved<b>₹0</b></span></footer></div><div className="allocation-card"><header><div><span>ALLOCATION</span><b>Virtual assets</b></div><i>100%</i></header><div className="allocation-ring"><div><strong>4</strong><small>assets</small></div></div><div className="allocation-legend">{holdings.map(item=><span key={item.coin}><i style={{background:item.color}}/><b>{item.coin}</b><em>{item.share}%</em></span>)}</div></div><div className={`exchange-card ${connected?"connected":""}`}><header><span>EXCHANGE CONNECTION</span><i>{connected?(connection?.canTrade?"TESTNET READY":"READ ONLY"):"NOT CONNECTED"}</i></header><div className="exchange-logo">B</div><h2>{connected?"Binance Spot Testnet":"Connect when you’re ready"}</h2><p>{connected?`${connection?.apiKeyHint} · ${connection?.canTrade?"Spot test trading permission verified":"Enable Spot trading on the Testnet key when needed"}`:"Paper trading works without an exchange. Testnet connection can be added separately."}</p>{connected?<><div className="permission-list"><span><i>✓</i> Account data verified</span><span><i>{connection?.canTrade?"✓":"!"}</i> {connection?.canTrade?"Spot test permission":"Trading permission off"}</span><span className="blocked"><i>×</i> Withdrawal API not implemented</span></div>{connection?.balances?.length?<div className="testnet-balances">{connection.balances.slice(0,3).map(item=><span key={item.asset}><b>{item.asset}</b><small>{Number(item.free).toLocaleString("en-US",{maximumFractionDigits:6})}</small></span>)}</div>:null}<div className="exchange-card-actions"><button disabled={exchangeBusy} onClick={refreshExchange}>{exchangeBusy?"Checking…":"Refresh"}</button><button disabled={exchangeBusy} onClick={disconnectExchange}>Disconnect</button></div></>:<button onClick={()=>{setExchangeError("");setConnect(true)}}>Connect Binance Testnet <span>→</span></button>}{exchangeError?<small className="exchange-inline-error">{exchangeError}</small>:<small>Credentials are encrypted and never displayed after connection.</small>}</div></section>
  <section className="holdings-section"><div className="wallet-section-head"><div><h2>Paper holdings</h2><p>Illustrative allocation based on simulated trades.</p></div><button onClick={()=>setHideSmall(value=>!value)}>{hideSmall?"Show all balances":"Hide small balances"}</button></div><div className="holdings-table"><header><span>ASSET</span><span>AMOUNT</span><span>VIRTUAL VALUE</span><span>ALLOCATION</span><span>24H</span></header>{visibleHoldings.map(item=><div key={item.coin}><span className="asset-name"><i style={{background:item.color}}>{item.symbol}</i><b>{item.coin}<small>{item.name}</small></b></span><span>{item.amount}</span><b>{item.value}</b><span className="allocation-bar"><i style={{width:`${item.share}%`,background:item.color}}/><small>{item.share}%</small></span><em>+{(item.share/10).toFixed(2)}%</em></div>)}</div></section>
  <section className="wallet-transactions" id="transactions"><div className="wallet-section-head"><div><h2>Recent wallet activity</h2><p>Paper movements and simulated settlements.</p></div><button onClick={()=>setShowAll(value=>!value)}>{showAll?"Show recent":"View all"}</button></div><div>{transactions.slice(0,showAll?transactions.length:3).map(item=><article key={item.time+item.coin}><i>{item.type.includes("BUY")?"↘":item.type.includes("SELL")?"↗":"+"}</i><span><b>{item.type} · {item.coin}</b><small>{item.time}</small></span><span><b>{item.amount}</b><small>{item.value}</small></span><em>{item.status}</em></article>)}</div></section><p className="ai-data-note">Paper wallet only · Account balance is saved; asset allocation and activity examples are illustrative · No real funds are held</p>
 </section></div>
 {funds&&<div className="wallet-modal-bg"><section className="funds-modal"><header><div><span>PAPER BALANCE</span><h2>Add virtual funds</h2></div><button disabled={fundsBusy} onClick={()=>setFunds(false)}>×</button></header><p>This changes your saved demo balance only. No payment or real money is involved.</p><label>Virtual amount<span>₹<input min="100" max="100000" type="number" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></span></label><div className="quick-funds">{[5000,10000,25000].map(value=><button className={amount===value?"active":""} onClick={()=>setAmount(value)} key={value}>₹{value.toLocaleString("en-IN")}</button>)}</div><div className="funds-preview"><span>Current balance<b>₹{balance.toLocaleString("en-IN")}</b></span><i>→</i><span>New balance<b>₹{(balance+amount).toLocaleString("en-IN")}</b></span></div>{fundsError&&<p className="credential-error">{fundsError}</p>}<button className="confirm-funds" disabled={fundsBusy||amount<100||amount>100000} onClick={addFunds}>{fundsBusy?"Saving…":"Add virtual funds"} <span>→</span></button></section></div>}
 {connect&&<div className="wallet-modal-bg"><section className="connect-modal"><header><div><span>SAFE TEST CONNECTION</span><h2>Connect Binance Testnet</h2></div><button disabled={exchangeBusy} onClick={()=>setConnect(false)}>×</button></header><div className="testnet-banner"><i>◇</i><p><b>Testnet only</b><span>Virtual assets only—this does not connect to a real-money account.</span></p></div><label>API Key<div><input autoComplete="off" type={showKey?"text":"password"} value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="Enter testnet API key"/><button type="button" onClick={()=>setShowKey(!showKey)}>{showKey?"Hide":"Show"}</button></div></label><label>Secret Key<div><input autoComplete="new-password" type="password" value={secret} onChange={e=>setSecret(e.target.value)} placeholder="Enter testnet secret"/></div></label><div className="api-permissions"><span><i>✓</i><b>Verify account data</b><small>Required</small></span><span><i>✓</i><b>Check Spot permission</b><small>Validated</small></span><span className="denied"><i>×</i><b>Withdrawal API</b><small>Not implemented</small></span></div>{exchangeError?<p className="credential-error">{exchangeError}</p>:<p className="credential-note">Your keys are encrypted server-side. Never paste them into chat or share them with anyone.</p>}<button className="connect-confirm" disabled={!apiKey||!secret||exchangeBusy} onClick={connectExchange}>{exchangeBusy?"Verifying Testnet…":"Verify & connect testnet"} <span>↗</span></button></section></div>}
 <nav className="ai-mobile-nav"><a href="/trade"><i>↗</i>Trade</a><a href="/trade/ai"><i>✦</i>AI</a><a href="/trade/bots"><i>◉</i>Bots</a><a className="active" href="/trade/wallet"><i>▰</i>Wallet</a><a href="/trade/settings"><i>⚙</i>Settings</a></nav>
 </main>
}
