"use client";

import { useCallback,useEffect,useMemo,useState } from "react";

const markets=[{id:"BTC",symbol:"₿",color:"#f5a623",signal:"NO TRADE",confidence:64},{id:"ETH",symbol:"◆",color:"#8293ff",signal:"BUY",confidence:81},{id:"SOL",symbol:"S",color:"#92ffc7",signal:"BUY",confidence:84},{id:"BNB",symbol:"B",color:"#f1d26a",signal:"NO TRADE",confidence:58}];
const money=(n:number)=>new Intl.NumberFormat("en-IN").format(n);

export default function AutoSetup(){
 const [step,setStep]=useState<"limits"|"review"|"active">("limits"),[capital,setCapital]=useState(10000),[risk,setRisk]=useState(1),[dailyLoss,setDailyLoss]=useState(3),[maxTrades,setMaxTrades]=useState(2),[confidence,setConfidence]=useState(80),[coins,setCoins]=useState(["BTC","ETH","SOL","BNB"]),[accepted,setAccepted]=useState(false),[activating,setActivating]=useState(false),[activationError,setActivationError]=useState("");
 const [rules,setRules]=useState({stop:true,target:true,daily:true,volatility:true});
 const [liveMarkets,setLiveMarkets]=useState(markets),[autoLog,setAutoLog]=useState("Waiting for first live scan…");
 const riskAmount=capital*risk/100,dailyAmount=capital*dailyLoss/100;
 const canReview=capital>=1000&&coins.length>0&&Object.values(rules).every(Boolean);
 const toggleCoin=(coin:string)=>setCoins(c=>c.includes(coin)?c.filter(x=>x!==coin):[...c,coin]);
 const toggleRule=(key:keyof typeof rules)=>setRules(r=>({...r,[key]:!r[key]}));
 const opportunities=useMemo(()=>liveMarkets.filter(m=>coins.includes(m.id)&&m.confidence>=confidence&&m.signal!=="NO TRADE"),[liveMarkets,coins,confidence]);
 const scan=useCallback(async()=>{try{const values=await Promise.all(coins.map(async id=>{const response=await fetch(`/api/signals?asset=${id}`,{cache:"no-store"});if(!response.ok)throw new Error();const data=await response.json();const base=markets.find(item=>item.id===id)!;return{...base,signal:data.signal,confidence:data.confidence,entry:data.entry,stopLoss:data.stopLoss,takeProfit:data.takeProfit}}));setLiveMarkets(values);const candidate=values.filter(item=>item.signal!=="NO TRADE"&&item.confidence>=confidence).sort((a,b)=>b.confidence-a.confidence)[0];if(!candidate){setAutoLog("NO TRADE · No setup currently passes both confidence and risk rules.");return}const response=await fetch("/api/trades",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({asset:candidate.id,side:candidate.signal,amount:Math.min(500,capital),entryPrice:candidate.entry,stopPrice:candidate.stopLoss,targetPrice:candidate.takeProfit,confidence:candidate.confidence})});const result=await response.json();setAutoLog(response.ok?`${candidate.signal} ${candidate.id} · ₹${Math.min(500,capital)} paper order saved · ${result.id}`:`BLOCKED · ${result.error||"Risk engine denied the order"}`)}catch{setAutoLog("Market scan offline · No order created.")}},[coins,confidence,capital]);
 useEffect(()=>{if(step!=="active")return;scan();const timer=window.setInterval(scan,30000);return()=>window.clearInterval(timer)},[step,scan]);
 const activate=async()=>{setActivating(true);setActivationError("");try{const response=await fetch("/api/account",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({mode:"auto",settings:{capital,maxRisk:risk,dailyLoss,maxPositions:maxTrades,minConfidence:confidence,stopLoss:rules.stop,takeProfit:rules.target,dailyStop:rules.daily,volatility:rules.volatility}})}),data=await response.json();if(!response.ok)throw new Error(data.error||"AI Auto could not be activated.");setStep("active")}catch(reason){setActivationError(reason instanceof Error?reason.message:"AI Auto could not be activated.")}finally{setActivating(false)}};
 return <main className="auto-setup-shell">
  <header className="auto-top"><a className="terminal-logo" href="/"><img src="/chatonyou-logo.png" alt="ChatOnYou"/><b>TRADE</b></a><div><i/> AI AUTO · PAPER MODE</div><a href="/trade/ai">×</a></header>
  <section className="auto-stepper"><span className={step==="limits"?"active":"done"}><i>{step==="limits"?"1":"✓"}</i><b>Set limits</b><small>Capital &amp; risk</small></span><em/><span className={step==="review"?"active":step==="active"?"done":""}><i>{step==="active"?"✓":"2"}</i><b>Safety review</b><small>Rules &amp; permission</small></span><em/><span className={step==="active"?"active":""}><i>3</i><b>Activate</b><small>Start watching</small></span></section>
  {step==="active"?<section className="auto-active-state"><div className="auto-orbit"><i>✦</i><b/><b/><b/></div><span>AI AUTO IS ACTIVE · PAPER ONLY</span><h1>Watching {coins.length} markets.<br/><em>Scanning every 30 seconds.</em></h1><p>Quant AI can act only inside the limits you approved. This V1 monitor runs while this page is open.</p><div className="auto-live-status"><header><span><i/> LIVE PAPER MONITOR</span><b>Protected</b></header><section>{liveMarkets.filter(m=>coins.includes(m.id)).map(m=><article key={m.id}><i style={{background:m.color}}>{m.symbol}</i><span><b>{m.id}/USDT</b><small>{m.signal}</small></span><strong>{m.confidence}%<small>confidence</small></strong><em className={m.confidence>=confidence&&m.signal!=="NO TRADE"?"ready":"wait"}>{m.confidence>=confidence&&m.signal!=="NO TRADE"?"ELIGIBLE":"WAIT"}</em></article>)}</section><footer><span>Minimum confidence <b>{confidence}%</b></span><span>Risk / trade <b>{risk}%</b></span><span>Daily stop <b>{dailyLoss}%</b></span></footer></div><div className="auto-safety-note"><i>✦</i><span><b>Last auto decision</b><small>{autoLog}</small></span></div><div className="auto-active-actions"><a href="/trade/ai">View AI activity <span>→</span></a><button onClick={()=>{setStep("limits");setAccepted(false)}}>Edit limits</button></div><small>AI may choose NO TRADE. That is a valid protective decision.</small></section>:
  <section className="auto-main">
   <aside className="auto-context"><span>CONTROL BEFORE AUTOMATION</span><h1>{step==="limits"?<>Tell AI exactly<br/><em>where to stop.</em></>:<>Review every<br/><em>hard limit.</em></>}</h1><p>{step==="limits"?"AI can analyse continuously, but it cannot exceed the capital and risk permissions you set.":"Once activated, these rules sit between every AI signal and every simulated order."}</p><div className="auto-flow-map"><span><i>✦</i><b>AI signal</b><small>BUY · SELL · NO TRADE</small></span><em>↓</em><span className="active"><i>◇</i><b>Risk engine</b><small>Your hard limits</small></span><em>↓</em><span><i>↗</i><b>Paper order</b><small>Only when approved</small></span></div><div className="auto-safety-note"><i>◇</i><span><b>No unrestricted access</b><small>Auto mode cannot change its own limits or bypass the risk engine.</small></span></div></aside>
   {step==="limits"?<section className="auto-form-card">
    <header><div><span>STEP 1 OF 3</span><h2>Set AI boundaries</h2></div><em>PAPER ONLY</em></header>
    <div className="auto-capital"><label>Trading capital <small>Virtual balance ₹10,842</small></label><div><b>₹</b><input type="number" min="1000" max="10842" step="500" value={capital} onChange={e=>setCapital(Math.min(10842,Math.max(0,Number(e.target.value))))}/><span>INR</span></div><nav>{[5000,7500,10000].map(n=><button className={capital===n?"active":""} onClick={()=>setCapital(n)} key={n}>₹{money(n)}</button>)}</nav></div>
    <div className="auto-sliders"><label><span>Max risk per trade <b>{risk}% · ₹{money(riskAmount)}</b></span><input type="range" min="0.5" max="2" step="0.5" value={risk} onChange={e=>setRisk(Number(e.target.value))}/><small>0.5% conservative <em>Recommended: 1%</em> 2% maximum</small></label><label><span>Daily max loss <b>{dailyLoss}% · ₹{money(dailyAmount)}</b></span><input type="range" min="1" max="5" value={dailyLoss} onChange={e=>setDailyLoss(Number(e.target.value))}/><small>AI stops for the day after this limit</small></label><label><span>Minimum AI confidence <b>{confidence}%</b></span><input type="range" min="70" max="95" step="5" value={confidence} onChange={e=>setConfidence(Number(e.target.value))}/><small>Higher confidence means fewer, more selective trades</small></label></div>
    <div className="auto-max-positions"><span>Maximum simultaneous trades</span><div>{[1,2,3].map(n=><button className={maxTrades===n?"active":""} onClick={()=>setMaxTrades(n)} key={n}>{n}<small>{n===1?"trade":"trades"}</small></button>)}</div></div>
    <div className="auto-markets"><header><span>Markets AI may trade</span><b>{coins.length} selected</b></header><div>{markets.map(m=><button className={coins.includes(m.id)?"active":""} onClick={()=>toggleCoin(m.id)} key={m.id}><i style={{background:m.color}}>{m.symbol}</i><span><b>{m.id}</b><small>Spot</small></span><em>{coins.includes(m.id)?"✓":"+"}</em></button>)}</div></div>
    <footer><p>{!canReview?"Select at least one market and keep all safety rules on.":"Your limits are ready for safety review."}</p><button disabled={!canReview} onClick={()=>setStep("review")}>Review safety rules <span>→</span></button></footer>
   </section>:<section className="auto-review-card">
    <header><div><span>STEP 2 OF 3</span><h2>Safety review</h2></div><button onClick={()=>setStep("limits")}>← Edit</button></header>
    <section className="auto-review-summary"><span>Trading capital<b>₹{money(capital)}</b></span><span>Risk / trade<b>{risk}% · ₹{money(riskAmount)}</b></span><span>Daily stop<b>{dailyLoss}% · ₹{money(dailyAmount)}</b></span><span>Max open positions<b>{maxTrades}</b></span><span>Confidence rule<b>{confidence}% minimum</b></span><span>Markets<b>{coins.join(" · ")}</b></span></section>
    <div className="auto-rule-list"><header>MANDATORY EXECUTION RULES <span>All must stay ON</span></header>{[{key:"stop",title:"Always use stop loss",desc:"Every entry gets a protective exit."},{key:"target",title:"Always use take profit",desc:"Profit targets are defined before entry."},{key:"daily",title:"Stop after daily-loss limit",desc:`AI pauses after ₹${money(dailyAmount)} simulated loss.`},{key:"volatility",title:"Disable during abnormal volatility",desc:"Unsafe market conditions block new orders."}].map(item=><button className={rules[item.key as keyof typeof rules]?"on":""} onClick={()=>toggleRule(item.key as keyof typeof rules)} key={item.key}><i>{rules[item.key as keyof typeof rules]?"✓":"!"}</i><span><b>{item.title}</b><small>{item.desc}</small></span><em/></button>)}</div>
    <section className="auto-ready-check"><div><i>{opportunities.length}</i><span><b>opportunities currently eligible</b><small>SOL and ETH meet the demo confidence rule.</small></span></div><p>AI is never required to trade. If no setup passes every check, it will choose <b>NO TRADE</b>.</p></section>
    <label className="auto-permission"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><i>✓</i><span><b>I approve these paper-trading limits</b><small>I understand results are simulated and do not guarantee real returns.</small></span></label>
    {activationError&&<p className="auto-activation-error" role="alert">{activationError}</p>}<button className="auto-activate" disabled={activating||!accepted||!Object.values(rules).every(Boolean)} onClick={activate}><span>✦</span> {activating?"Saving safety rules…":"Activate AI Auto in paper mode"} <b>→</b></button>
    {!accepted&&<small className="auto-review-help">Approve the paper-mode permission to activate.</small>}
   </section>}
  </section>}
 </main>
}
